### ISSUE TITLE
Components with only optional props lose props type if strict mode is disabled

### ISSUE THREAD

**Issue by john-eos** [nuxt/nuxt#29041]
### Environment

```
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
```

### Reproduction

https://stackblitz.com/edit/github-z6juqt?file=components%2FTest.vue

`npm run typecheck` in terminal

```
components/Test.vue:8:17 - error TS2339: Property 'optionalStr' does not exist on type 'CreateComponentPublicInstanceWithMixins<ToResolvedProps<{}, {}>, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, VNodeProps & AllowedComponentProps & ComponentCustomProps & Readonly<...> & Readonly<...>, ... 16 more ..., {}>'.

8     <span v-if="optionalStr">{{ optionalStr }}</span>
                  ~~~~~~~~~~~
```

### Describe the bug

After upgrading from Nuxt 3.12.3 to 3.13.2, these TS errors showed up in every component that only uses optional props. The error disappears if we add a single required prop or enable TS strict mode.

### Additional context

The issue doesn't seem to be present in a pure Vue/Vite project:

https://stackblitz.com/edit/vitejs-vite-ece16d?file=src%2Fcomponents%2FHelloWorld.vue

**Comment by john-eos** [comment]
This was caused by https://github.com/vuejs/language-tools/issues/4704 which was fixed in Vue 3.5.7
