### ISSUE TITLE
nuxt.vueApp.runWithContext is not a function

### ISSUE THREAD

**Issue by gyhyfj** [nuxt/nuxt#20901]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.0
- Package Manager:  pnpm@8.4.0
- Builder:          vite
- User Config:      modules, vite, css, imports, pinia, sitemap, app, ignore, telemetry, appConfig, devServer, nitro
- Runtime Modules:  @nuxtjs/tailwindcss@6.6.6, @pinia/nuxt@0.4.8, @pinia-plugin-persistedstate/nuxt@1.1.1, @element-plus/nuxt@1.0.4, @nuxtjs/robots@3.0.0, nuxt-simple-sitemap@2.4.11
- Build Modules:    -

### Reproduction

-

### Describe the bug

Cannot work after updating from 3.4.2 to 3.5.0 when run `dev`

This is  error msg in terminal:

```pwsh
ℹ Vite client warmed up in 8568ms
[nitro] ✔ Nitro built in 7719 ms
✔ Vite server hmr 20 files in 10116.675ms
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] nuxt.vueApp.runWithContext is not a function
  at callWithNuxt (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\nuxt@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4\node_modules\nuxt\dist\app\nuxt.js:210:24)
  at Object.runWithContext (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\nuxt@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4\node_modules\nuxt\dist\app\nuxt.js:32:29) 

  at applyPlugin (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\nuxt@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4\node_modules\nuxt\dist\app\nuxt.js:111:37)
  at Module.applyPlugins (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\nuxt@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4\node_modules\nuxt\dist\app\nuxt.js:123:21)  
  at createNuxtAppServer (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\nuxt@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4\node_modules\nuxt\dist\app\entry.js:29:35)  
  at __vite_ssr_exports__.default (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\nuxt@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4\node_modules\nuxt\dist\app\entry.js:74:41)
  at default (/D:/GitRepo/serverless/frontend-monorepo/node_modules/.pnpm/@nuxt+vite-builder@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4_vue@3.3.2/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:31:24)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.renderToString (/D:/GitRepo/serverless/frontend-monorepo/node_modules/.pnpm/vue-bundle-renderer@1.0.3/node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)
  at async /D:/GitRepo/serverless/frontend-monorepo/apps/dalle-nuxt3/.nuxt/dev/index.mjs:3201:21
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] nuxt.vueApp.runWithContext is not a function
  at callWithNuxt (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\nuxt@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4\node_modules\nuxt\dist\app\nuxt.js:210:24)
  at Object.runWithContext (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\nuxt@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4\node_modules\nuxt\dist\app\nuxt.js:32:29) 

  at applyPlugin (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\nuxt@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4\node_modules\nuxt\dist\app\nuxt.js:111:37)
  at Module.applyPlugins (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\nuxt@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4\node_modules\nuxt\dist\app\nuxt.js:123:21)  
  at createNuxtAppServer (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\nuxt@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4\node_modules\nuxt\dist\app\entry.js:29:35)  
  at __vite_ssr_exports__.default (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\nuxt@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4\node_modules\nuxt\dist\app\entry.js:74:41)
  at default (/D:/GitRepo/serverless/frontend-monorepo/node_modules/.pnpm/@nuxt+vite-builder@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4_vue@3.3.2/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:31:24)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.renderToString (/D:/GitRepo/serverless/frontend-monorepo/node_modules/.pnpm/vue-bundle-renderer@1.0.3/node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)
  at async /D:/GitRepo/serverless/frontend-monorepo/apps/dalle-nuxt3/.nuxt/dev/index.mjs:3201:21
```

This is error msg in browser:

```pwsh
500
__vite_ssr_import_0__.hasInjectionContext is not a function

at Module.useRoute (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\nuxt@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4\node_modules\nuxt\dist\app\composables\router.js:21:29)
at setup (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\nuxt@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4\node_modules\nuxt\dist\app\components\nuxt-root.vue:35:63)
at _sfc_main.setup (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\nuxt@3.5.0_@types+node@20.1.7_sass@1.62.0_typescript@5.0.4\node_modules\nuxt\dist\app\components\nuxt-root.vue:89:23)
at callWithErrorHandling (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\@vue+runtime-core@3.2.47\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:171:22)
at setupStatefulComponent (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\@vue+runtime-core@3.2.47\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7194:29)
at setupComponent (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\@vue+runtime-core@3.2.47\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7149:11)
at renderComponentVNode (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\@vue+server-renderer@3.2.47_vue@3.2.47\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:628:17)
at renderToString (D:\GitRepo\serverless\frontend-monorepo\node_modules\.pnpm\@vue+server-renderer@3.2.47_vue@3.2.47\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:906:26)
at Object.renderToString$1 [as renderToString] (/D:/GitRepo/serverless/frontend-monorepo/apps/dalle-nuxt3/.nuxt/dev/index.mjs:3129:24)
at Object.renderToString (/D:/GitRepo/serverless/frontend-monorepo/node_modules/.pnpm/vue-bundle-renderer@1.0.3/node_modules/vue-bundle-renderer/dist/runtime.mjs:177:40)
```

**Comment by danielroe** [comment]
You have an older version (or multiple versions) of vue installed. Try explicitly requiring vue 3.3.2+, refresh your lockfile, or use npm/pnpm overrides or yarn resolutions to force the correct version.

**Comment by gyhyfj** [comment]
Sorry but it doesn't work because it's a monorepo on pnpm, with another app depending on vue 3.2, that' why it cannot resolve vue 3.3 as expected. So I can just stay nuxt 3.4.2 as stable verson in future until #14146 is resolved .

**Comment by fabianwohlfart** [comment]
I have this problem with freshly installed nuxt via `npx nuxt@latest install my-app` and pnpm.
Yarn works.
Is it a pnpm problem?

**Comment by gyhyfj** [comment]
> I have this problem with freshly installed nuxt via `npx nuxt@latest install my-app` and pnpm. Yarn works. Is it a pnpm problem?

Yes, if you start a new nuxt3 project, you'd better don't use pnpm and monorepo, unitil 14146 is resolved.

**Comment by reslear** [comment]
fix: `pnpm add vue`

**Comment by Nicolas-Yazzoom** [comment]
I had the issue when upgrading from `"nuxt": "^3.4.3"`  to `"nuxt": "^3.6.2"`. Due to some issues with an earlier version, I had this in my `package.json`:

```
  "overrides": {
    "vue": "latest"
  },
```

Removing it solved the issue for me. It seems my original issue for adding this was also resolved some time ago.

**Comment by weiquanju** [comment]
My project use monorepo by pnpm workspace. Nuxt version is 3.6.5. **Installing a module** can solve this problem. Why? @danielroe 

```shell
pnpm install pinia
```

**Comment by jastaffen** [comment]
Hi I was having this issue while running the latest version of nuxt (as of writing this it was 3.6.5) with npm and the solve was adding "vue": "^3.3.0" to my package.json dependencies. @danielroe any ideas why that may be? Is this a breaking change / regression between older (<3.6.5) and newer versions (>=3.6.5) of nuxt 3? In my case, the errors I was getting were both: 

```
[nuxt] [request error] [unhandled] [500] nuxt.vueApp.runWithContext is not a function                                                                                                              
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_0__.hasInjectionContext is not a function   
```

**Comment by danielroe** [comment]
@jastaffen it's not a breaking change as such; it's just that somehow you have an older version of Vue installed than the one Nuxt depends on. Try refreshing your lockfile.
