### ISSUE TITLE
Module resolution error for pako after upgrading from 3.15.2 to 3.15.3

### ISSUE THREAD

**Issue by aveliino88** [nuxt/nuxt#30769]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v20.14.0`
- Nuxt Version:     `3.15.3`
- CLI Version:      `3.20.0`
- Nitro Version:    `2.10.4`
- Package Manager:  `npm@10.9.2`
- Builder:          `-`
- User Config:      `modules`, `ssr`, `devtools`, `app`, `css`, `site`, `colorMode`, `runtimeConfig`, `build`, `compatibilityDate`, `vite`, `postcss`, `logLevel`, `cookieControl`, `eslint`, `image`, `robots`, `seo`, `shadcn`, `sitemap`
- Runtime Modules:  `@nuxtjs/color-mode@3.5.2`, `@pinia/nuxt@0.8.0`, `shadcn-nuxt@0.11.3`, `@nuxt/image@1.9.0`, `@nuxtjs/seo@2.1.0`, `@nuxt/eslint@0.7.5`, `@dargmuesli/nuxt-cookie-control@8.5.0`
- Build Modules:    `-`

### Reproduction

**Reproduction:**
- Upgrade Nuxt from 3.15.2 to 3.15.3
- Error occurs during route navigation: Cannot find module './lib/utils/common'
- Error appears to be related to pako dependency resolution

**Current Behavior:**
Error during navigation:

### Describe the bug

After upgrading from Nuxt 3.15.2 to 3.15.3, the application immediately fails with a module resolution error when trying to access the development server.

Steps to reproduce:
1. Run `npm run dev`
2. Access `localhost:3000`
3. Application immediately fails with a 500 error and the following error message:

ERROR  Cannot find module './lib/utils/common'
Require stack:
- C:\Git\nuxtapp\app\pako
- C:\Git\nuxtapp\app\pako
- C:\Git\nuxtapp\app\pako

Require stack:
- pako
at Function._resolveFilename (node:internal/modules/cjs/loader:1145:15)
at Function._load (node:internal/modules/cjs/loader:986:27)
at Module.require (node:internal/modules/cjs/loader:1233:19)
at require (node:internal/modules/helpers:179:18)
at pako:4:17
at ViteNodeRunner.runModule (/C:/Git/nuxtapp/app/node_modules/vite-node/dist/client.mjs:399:11)
at ViteNodeRunner.directRequest (/C:/Git/nuxtapp/app/node_modules/vite-node/dist/client.mjs:381:16)

Notable details:
- Error occurs in Vite's node runner during development
- Multiple identical entries in require stack suggesting a circular dependency issue
- The error appears immediately on initial page load without any user interaction
- Error happens during the development server runtime
- The dependency tree shows multiple versions of pako:
  - pako@0.2.9 (from nuxt-og-image → satori → linebreak → unicode-trie)
  - pako@1.0.11 (from pdf-lib)

Attempted fixes:
- Adding package resolutions for pako
- Clean install of dependencies
- Clearing npm cache

None of these resolved the issue. The application works correctly in 3.15.2 but fails immediately in 3.15.3, suggesting a regression in how Vite-node handles module resolution in the development server.

### Logs

```shell-script

```

**Comment by N1cE-me** [comment]
Same issue with external lib [crypto-js](https://www.npmjs.com/package/crypto-js).
And it's looks as 
```
[nuxt] [request error] [unhandled] [500] [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables
```
without any error stack

**Comment by danielroe** [comment]
this should be resolved in https://github.com/nuxt/nuxt/pull/30802

**Comment by danielroe** [comment]
@nisu then it is a different issue, as the linked PR fully reverted the change.

do you have a reproduction?

**Comment by NisuSan** [comment]
> [@Nisu](https://github.com/Nisu) then it is a different issue, as the linked PR fully reverted the change.
> 
> do you have a reproduction?

This is a problem with building the project. The pachages in server/node_modules looks like relative links to packages from main node_modules in project root. After deploy to the server links gone and project does not working.
