### ISSUE TITLE
bug? [request error] [unhandled] [500] Cannot find module './node.js'

### ISSUE THREAD

**Issue by ijkml** [nuxt/nuxt#29991]
### Environment

- Operating System: `Linux`
- Node Version:     `v22.6.0`
- Nuxt Version:     `3.14.1592`
- CLI Version:      `3.15.0`
- Nitro Version:    `2.10.4`
- Package Manager:  `pnpm@9.13.2`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `nuxt-umami@3.0.0`
- Build Modules:    `-`

### Reproduction

Stackblitz: https://stackblitz.com/github/ijkml/nuxt-umami-docs/tree/savepoint-2
Repo with commit: https://github.com/ijkml/nuxt-umami-docs/compare/savepoint...savepoint-2

Clone `savepoint`
  - dev: works
  - build: works.

Clone `savepoint-2`:
  - dev: error 500
  - build: works.

### Describe the bug

TLDR: module works with v3.13, dev and build; module breaks dev with v3.14, but build passes.

I'm running into a weird issue upgrading from Nuxt `3.13` to `3.14`. Starting the dev server throws a 500 (see logs).

There is no file at `/home/ml/Workspace/nuxt-umami-docs/debug`, and none of my files reference it.
But, the interesting part, `nuxt build` runs without any error. Now, if I remove (the only module) `nuxt-umami`, the dev server starts fine.
I've also taken the time to test `nuxt-umami` on other projects with Nuxt 3.14, no errors. So this is probably a _module-v-layer_ issue.

I'll appreciate any help I can get. Thank you!

### Logs

```shell-script
ERROR  [nuxt] [request error] [unhandled] [500] Cannot find module './node.js'
Require stack:
- /home/ml/Workspace/nuxt-umami-docs/debug


 ERROR  [nuxt] [request error] [unhandled] [500] Cannot find module './node.js'
Require stack:
- /home/ml/Workspace/nuxt-umami-docs/debug
```

**Comment by danielroe** [comment]
I think this is likely the same as https://github.com/nuxt/nuxt/issues/30749 - with probably the same workaround - can you try configuring `vite.ssr.noExternal`?
