### PR TITLE
fix(types): sync vue type augmentations with Vue 2.7

### PR DESCRIPTION
**Pull request by rchl**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Fixing an error:

```
../../node_modules/@nuxt/types/app/vue.d.ts:21:13 - error TS2428: All declarations of 'ComponentOptions' must have identical type parameters.

21   interface ComponentOptions<

../../node_modules/vue/types/options.d.ts:168:18 - error TS2428: All declarations of 'ComponentOptions' must have identical type parameters.

168 export interface ComponentOptions<
                     ~~~~~~~~~~~~~~~~
```

Note that I haven't tested this probably and I admit I don't **fully** understand the intentions here so this needs some testing.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by rchl** [comment]
As mentioned in #9239, I've verified that this issue happens in Vue 2.7 but not in Vue 2.6.

Are we fine with going forward with types being only Vue 2.7-compatible. It might be the case already as Nuxt ships with VueRouter version that relies on Vue 2.7 already and there are also issues with importing `Vuex` in this package when using Vue 2.6.

```
node_modules/@nuxt/types/app/index.d.ts:5:28 - error TS2307: Cannot find module 'vuex' or its corresponding type declarations.

5 import type { Store } from 'vuex'
```

So, either we just revert #9230 or use take this PR which reverts the breaking change at least or we could go with something like https://github.com/rchl/nuxt/commit/0feb9fe1fa4420630958edd91800734671ee975a which adapts the changes to make them Vue 2.7 compatible.

**Review by danielroe — DISMISSED** [review]

**Comment by rchl** [comment]
Just for the record (since we're discussing this in private anyway), with the current state of the code the inferring of types of properties returned from `asyncData` (the intent of the original https://github.com/nuxt/nuxt/pull/9239 fix) still doesn't work.

**Comment by danielroe** [comment]
That is a different issue, and not caused by the fix I pushed here, which is correct as far as I can tell, but rather by the fact that there are other parts of these declarations that also need to be updated to work with Vue 2.7.

**Comment by rchl** [comment]
I know but we have two ways we can go here. Either just fix the crash or fix the crash and support inferring of asyncData return values.

The latter seems complicated and potentially risky (Vue types are a little brittle).

So IMO it's an option to just fix the crash without the support for inferring and I feel like this is much safer.

Not duplicating the `asyncData` properties in `data` has potential for breakage and in some cases different runtime behavior anyway. While in theory `asyncData` should always run first and set the properties on `data`, in practice we've seen crashes reported to Sentry when we forgot to duplicate those properties in `data`. This is potentially only an issue in very broken environments but still it can make a difference.

**Review by danielroe — APPROVED** [review]
