### ISSUE TITLE
resolveConfig with tailwindcss does not work in 3.15.3

### ISSUE THREAD

**Issue by segidev** [nuxt/nuxt#30795]
### Environment

- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     3.15.2
- CLI Version:      3.20.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.8.3
- Builder:          -
- User Config:      modules, devtools, app, css, colorMode, runtimeConfig, routeRules, watch, experimental, compatibilityDate, vite, primevue, tailwindcss
- Runtime Modules:  @primevue/nuxt-module@4.2.5, @nuxtjs/tailwindcss@6.13.1, @nuxtjs/color-mode@3.5.2, @nuxt/eslint@0.7.5
- Build Modules:    -

### Reproduction

I setup two examples on Stackblitz, checkout the `app.vue`:
- [Working with 3.15.2](https://stackblitz.com/edit/github-5q6fvymf?file=app.vue)
- [Failing with 3.15.3](https://stackblitz.com/edit/github-5q6fvymf-otol8ppp?file=app.vue)

### Describe the bug

Since version `3.15.3` the `resolveConfig` method does no longer work

### Additional context

I am using https://nuxt.com/modules/tailwindcss. **It works fine with 3.15.2 and older.**

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] Cannot find module './lib/public/resolve-config'
```

**Comment by danielroe** [comment]
We plan to re-implement the PR that led to this bug. If you were experiencing it, would you test out [the pending PR](https://github.com/nuxt/nuxt/pull/30923) with `npm i https://pkg.pr.new/nuxt@30923`? 🙏
