### ISSUE TITLE
useId modules error

### ISSUE THREAD

**Issue by Fiyuva** [nuxt/nuxt#28837]
### Discussed in https://github.com/nuxt/nuxt/discussions/28835

<div type='discussions-op-text'>

<sup>Originally posted by **Fiyuva** September  4, 2024</sup>
 Hello, I get this error when I try to build after the latest update.

ERROR  Nuxt Build Error: node_modules/nuxt/dist/app/composables/id.js (1:9): "useId" is not exported by "node_modules/vue/dist/vue.runtime.esm-bundler.js", imported by "node_modules/nuxt/dist/app/composables/id.js".

in dev mode it says

Uncaught (in promise) SyntaxError: The requested module '/_nuxt/node_modules/vue/dist/vue.runtime.esm-bundler.js?v=66f24f9d' does not provide an export named 'useId' (at id.js:1:10)

`{
  "type": "module",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.6.0",
    "@fortawesome/free-brands-svg-icons": "^6.6.0",
    "@fortawesome/free-regular-svg-icons": "^6.6.0",
    "@fortawesome/free-solid-svg-icons": "^6.6.0",
    "@fortawesome/vue-fontawesome": "^3.0.8",
    "@nuxtjs/color-mode": "^3.4.4",
    "@nuxtjs/i18n": "^8.5.1",
    "@types/bootstrap": "^5.2.10",
    "@vite-pwa/nuxt": "^0.10.4",
    "bootstrap": "^5.3.3",
    "eslint": "^9.9.1",
    "eslint-plugin-security-node": "^1.1.4",
    "nuxt": "^3.13.1",
    "nuxt-aos": "^1.2.5",
    "sweetalert2": "^11.6.13",
    "typescript": "^5.5.4",
    "vue-tsc": "^2.1.4"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.5.4",
    "@types/crypto-js": "^4.2.2",
    "crypto-js": "^4.2.0",
    "eslint-plugin-anti-trojan-source": "^1.1.1",
    "flag-icons": "^7.2.3",
    "nuxt-purgecss": "^2.0.0",
    "pinia": "^2.2.2",
    "sass": "^1.78.0",
    "vue-recaptcha": "^3.0.0-alpha.6"
  },
  "resolutions": {
    "@nuxt/kit": "3.0.0-rc.13"
  },
  "overrides": {
    "vue": "latest"
  }
}
`

</div>

**Comment by danielroe** [comment]
Make sure you have the latest version of Vue in your project (check your lock file). `latest` is often not updated by package managers.

**Comment by leosin** [comment]
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/vue@3.4.37_typescript@5.5.4/node_modules/vue/dist/vue.runtime.esm-bundler.js?v=b0613c4f' does not provide an export named 'useId' (at id.js?v=b0613c4f:1:10)

when i update to 3.13.1 from 3.12.4...

- Operating System: Darwin
- Node Version:     v20.16.0
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.8.0

**Comment by danielroe** [comment]
You have Vue 3.4. Please upgrade to Vue 3.5 and you will be good to go.

**Comment by m3hari** [comment]
I hit this upgrading from `3.11.0` to `3.11.1`; the latest vue requirement is understandable. The only surprise is a patch version introduces an issue.

**Comment by m3hari** [comment]
It's not quite the same stack trace, but it's very similar; it could help debug.

```
'TypeError: __vite_ssr_import_2__.useId is not a function\n    
at callWithErrorHandling (/project/node_modules/.pnpm/@vue+runtime-core@3.4.27/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:195:19)\n    
at setupStatefulComponent (/project/node_modules/.pnpm/@vue+runtime-core@3.4.27/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7572:25)\n   
at setupComponent (/project/node_modules/.pnpm/@vue+runtime-core@3.4.27/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7533:36)\n    
at renderComponentVNode (/project/node_modules/.pnpm/@vue+server-renderer@3.4.27_vue@3.4.27/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:15)\n    
at renderVNode (/project/node_modules/.pnpm/@vue+server-renderer@3.4.27_vue@3.4.27/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:755:14)\n   
at renderVNodeChildren (/project/node_modules/.pnpm/@vue+server-renderer@3.4.27_vue@3.4.27/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:771:5)\n    
at renderVNode (/project/node_modules/.pnpm/@vue+server-renderer@3.4.27_vue@3.4.27/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:743:7)\n    
at renderVNodeChildren (/project/node_modules/.pnpm/@vue+server-renderer@3.4.27_vue@3.4.27/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:771
```

**Comment by AnthonyRuelle** [comment]
> Make sure you have the latest version of Vue in your project (check your lock file). `latest` is often not updated by package managers.
> 
> Also, why have you pinned Nuxt kit at a pre-v3 version?!


Hello, 

I have the same problem as described above. 

The overrides of vue latest is necessary for people using npm and using pinia...

(https://pinia.vuejs.org/ssr/nuxt.html#Installation)

**Comment by AnthonyRuelle** [comment]
This solution worked for me: 

Remove package_lock and folder node_modules
Reinstall your dependencies 

(Works leaving with overrides vue :) )

**Comment by danielroe** [comment]
Closing as this is not a Nuxt bug per se, but caused by your package manager installing an old version of Vue even though Nuxt depends on a newer one.

**Comment by Fiyuva** [comment]
> This solution worked for me:
> 
> Remove package_lock and folder node_modules Reinstall your dependencies
> 
> (Works leaving with overrides vue :) )

it worked for me! Thank you

**Comment by Fiyuva** [comment]
> Make sure you have the latest version of Vue in your project (check your lock file). `latest` is often not updated by package managers.
> 
> Also, why have you pinned Nuxt kit at a pre-v3 version?!

The last time I updated it, it was in this version.

**Comment by agracia-foticos** [comment]
remove package.lock and node_modules not work for me

https://github.com/tailwindlabs/headlessui/issues/3463

**Comment by agracia-foticos** [comment]
and put  "overrides": {
    "nuxt": {
      "vue": "latest"
    }
  } in package.json neither.
Vue version 3.5.3 and nuxt version 3.13.1

**Comment by fnacarellidev** [comment]
Upgrading Vue to 3.5 solved for me, thank you @danielroe :)

**Comment by snakysnake** [comment]
I have the same issue... Can someone help me fix it please? I looked in package.json and I don't even have "vue" in my project. Only nuxt.
```
node_modules/nuxt/dist/app/composables/id.js (1:9): "useId" is not exported by "node_modules/vue/dist/vue.runtime.esm-bundler.js", imported by "node_modules/nuxt/dist/app/composables/id.js
```
I have no idea how to fix it, please help me.

**Comment by danielroe** [comment]
@snakysnake Ensure you have the latest version of Vue. You can run npm i vue.

**Comment by snakysnake** [comment]
> @snakysnake Ensure you have the latest version of Vue. You can run npm i vue.

I see that I have some conflict when trying to ```npm i vue@latest```.
I try fixing it by adding ```--legacy-peer-deps```. Let's see what happens...

**Comment by snakysnake** [comment]
Ok... I guess you are right, I need the latest version of vue.
But when i try to ```npm i vue@latest``` I get an error:
```
npm error code EOVERRIDE
npm error Override for vue@3.5.6 conflicts with direct dependency
npm error A complete log of this run can be found in: .../.npm/_logs/2024-09-18T19_18_27_071Z-debug-0.log
```
Can someone help me debug this please? Thank you.

**Comment by makerovski** [comment]
> This solution worked for me:
> 
> Remove package_lock and folder node_modules Reinstall your dependencies
> 
> (Works leaving with overrides vue :) )

Worked for me! How could I forget it

**Comment by dariuspilapil-swaydev** [comment]
I was able to fix this by deleting `node_modules` and `package-lock.json`, making the following updates to `package.json`, then reinstalling:

- change nuxt dep to "^3.13.1"
- change vue dep to "^3.5"
- add "overrides": { "nuxt": { "vue": "^3.5" } }
