### ISSUE TITLE
4.5.1: app.config-declared component variant no longer type-checks (TS2322) — works on 4.5.0, still broken on 4.5.2

### ISSUE THREAD

**Issue by csechuan** [nuxt/nuxt#35996]
### Environment

- `nuxt`: 4.5.0 (working) → 4.5.1 / 4.5.2 (broken)
- `@nuxt/ui`: 4.10.0 (unchanged across the bump — ruled out as cause, see below)
- `vue-tsc` via `nuxt typecheck`
- App config declares a custom Nuxt UI variant, e.g.:

```ts
// app.config.ts
export default defineAppConfig({
  ui: {
    formField: {
      variants: {
        orientation: {
          action: 'flex items-center justify-between gap-4',
        },
      },
    },
  },
})
```

### Bug report

On `nuxt@4.5.0`, a template usage of the custom variant type-checks fine:

```vue
<UFormField orientation="action">...</UFormField>
```

On `nuxt@4.5.1` and `4.5.2`, the identical file/config, unchanged, fails `vue-tsc` with:

```
error TS2322: Type '"action"' is not assignable to type '"vertical" | "horizontal" | undefined'.
```

Runtime is unaffected — only the generated component prop type stops including the app.config-declared variant key.

### Isolation

- Two CI runs on the same commit range, ~4 minutes apart, touching neither the `.vue` file nor `app.config.ts`: `nuxt@4.5.0` green, `nuxt@4.5.1` red with the above error.
- `@nuxt/ui` is pinned at `4.10.0` in both runs (unchanged) — this rules out https://github.com/nuxt/ui/issues/6524 (a related-looking but distinct regression in `@nuxt/ui` itself, already fixed there via nuxt/ui#6531 well before 4.10.0).
- Locally re-verified against `nuxt@4.5.2` (latest as of writing): identical 2 errors, same lines. 4.5.2's changelog has no entries touching tsconfig/app-config type generation, consistent with this.
- Best current suspect (unconfirmed): https://github.com/nuxt/nuxt/pull/35673 ("Don't reference app config sources in shared and node tsconfigs"), the only app-config/type-generation-adjacent change in the 4.5.1 changelog. The PR's own description states no regression is expected for app-context files, so this may point elsewhere in the type-gen pipeline — flagging as the most likely lead, not a confirmed cause.

### Reproduction

1. `npx nuxi@latest init repro && cd repro`
2. Install `@nuxt/ui`, add a custom `formField.variants.orientation` key to `app.config.ts` as above.
3. Use `<UFormField orientation="action">` in any page.
4. `nuxt typecheck` on `nuxt@4.5.0` → passes.
5. Bump to `nuxt@4.5.1` (or `4.5.2`) → `nuxt typecheck` fails with TS2322 on the same line.

Happy to provide a minimal repro repo if useful.

**Comment by danielroe** [comment]
I couldn't reproduce with the steps you gave.

**Comment by captain-jack-sparrow909** [comment]
@csechuan This may be a useful case for BugBonsai, an open-source CLI I’m beta-testing that reduces a failing JS/TS project while rerunning the failure after every accepted deletion.
If you still have the failing project locally, this bounded run may help produce the minimal repository requested above:

```
  npx bugbonsai@beta \
  --match "TS2322" \
  --max-runs 100 \
  -- npx nuxt typecheck
```
It runs locally, has no telemetry, and never modifies the source project. Please review generated files before sharing them. Nuxt support is experimental, so an unsuccessful run is useful evidence too. You do not need to send me source or logs.
Safe workflow: https://github.com/captain-jack-sparrow909/BugBonsai/blob/main/docs/early-adopter-guide.md
Full disclosure: I’m the BugBonsai maintainer.

**Comment by csechuan** [comment]
Root cause found, and it explains the failed reproduction: the bug is **declaration-order dependent**, so it appears or vanishes depending on the order TypeScript loads two generated `.d.ts` files.

### What 4.5.1 changed

`4935d4b1` (#35673, "don't reference app config sources in shared and node tsconfigs") split the generated app-config declaration into two files:

- `.nuxt/types/app.config.d.ts` — imports the user's `app.config.ts` (`cfg0`), so `AppConfig` **includes** user-declared variants.
- `.nuxt/types/shared-app.config.d.ts` — new in 4.5.1, deliberately does **not** import it, so `AppConfig` carries framework defaults only.

Both augment the *same* interface in the *same* module:

```ts
// types/app.config.d.ts
declare module '@nuxt/schema' {
  interface AppConfig extends MergedAppConfig<ResolvedAppConfig, CustomAppConfig> {}
}

// types/shared-app.config.d.ts
declare module '@nuxt/schema' {
  interface AppConfig extends MergedAppConfig<typeof inlineConfig, CustomAppConfig> {}
}
```

Both are reachable from one program: `.nuxt/nuxt.d.ts:14` references the first, and `.nuxt/nuxt.shared.d.ts:3` + `.nuxt/nuxt.node.d.ts:13` reference the second.

### Why it is silent, and why it is order-dependent

Two declarations of the same interface property with different types is `TS2717` — but Nuxt's generated tsconfig sets `skipLibCheck: true`, so the conflict is never reported. TypeScript then resolves the property to whichever declaration it loaded **first**.

Minimal, framework-free reproduction of exactly that (three files, `skipLibCheck: true`):

```ts
// full.d.ts
declare module 'fake-schema' {
  interface AppConfig { ui: { formField: { variants: { orientation: { vertical: string; horizontal: string; action: string } } } } }
}
// bare.d.ts
declare module 'fake-schema' {
  interface AppConfig { ui: { formField: { variants: { orientation: { vertical: string; horizontal: string } } } } }
}
// use.ts
import type { AppConfig } from 'fake-schema';
type Orientation = keyof AppConfig['ui']['formField']['variants']['orientation'];
const x: Orientation = 'action';
```

- `include: ["full.d.ts", "bare.d.ts", "use.ts"]` → **passes**.
- `include: ["bare.d.ts", "full.d.ts", "use.ts"]` → **fails**, with the exact error from this issue:

```
use.ts(3,7): error TS2322: Type '"action"' is not assignable to type '"horizontal" | "vertical"'.
```

- With `skipLibCheck: false`, both orders instead surface the real conflict, `TS2717: Subsequent property declarations must have the same type.`

So the reproduction is not "does your app use `@nuxt/ui` + `app.config`", it is "does your program happen to pull `nuxt.shared.d.ts` / `nuxt.node.d.ts` before `nuxt.d.ts`". That is why the same config type-checks for you and not for us. Our setup, if it helps pin the ordering: bun-workspace monorepo, `apps/web` is `ssr: false`, checked with `nuxt typecheck` (solution-style `tsconfig.json` with `files: []` + `references` to app/server/shared/node), TypeScript 6.0.3, vue-tsc 3.3.9.

### Suggested direction

The shared/node declaration only needs to *avoid importing* the user's `app.config`; it does not need to *restate* `AppConfig` with a narrower type. As long as it declares the same interface, it is a latent conflict that `skipLibCheck` hides and load order decides. Options, roughly in order of how surgical they are:

1. Have `sharedAppConfigDeclarationTemplate` augment a distinct interface (e.g. `SharedAppConfig`) that the shared/node programs consume, leaving `AppConfig` with exactly one declaration.
2. Keep one declaration but make the shared variant additive-only — omit the keys it cannot resolve rather than re-declaring them from `inlineConfig`.
3. Failing both, make the conflict visible instead of order-dependent, so it fails loudly rather than silently narrowing a user's types.

Happy to test a patch against our repo — it reproduces deterministically here.

**Comment by captain-jack-sparrow909** [comment]
@csechuan , Thanks for the excellent root-cause analysis and three-file reproduction. 
For BugBonsai’s beta feedback only: did BugBonsai contribute to producing that reproduction, or did you reduce it manually? 
Either answer is useful—no source or logs needed. If you tried it, a simple outcome such as useful, too large, or could not complete is enough.

**Comment by SnowingFox** [comment]
Opened a PR to address this: https://github.com/nuxt/nuxt/pull/36043
