### ISSUE TITLE
Cannot find module './moment-timezone' after upgrading to v3.15.3

### ISSUE THREAD

**Issue by acemero-dev** [nuxt/nuxt#30749]
### Environment

- Operating System: Linux
- Node Version:     v23.1.0
- Nuxt Version:     3.15.3
- CLI Version:      3.20.0
- Nitro Version:    2.10.4
- Package Manager:  bun@1.1.37
- Builder:          -
- User Config:      future, srcDir, components, devtools, features, app, experimental, dev, ssr, dir, imports, alias, vite, runtimeConfig, css, modules, dayjs, security, googleFonts, piniaPersistedstate, nitro, elementPlus, image, lodash, tailwindcss, postcss, build, hooks, compatibilityDate
- Runtime Modules:  @pinia/nuxt@0.5.5, @pinia-plugin-persistedstate/nuxt@1.2.1, @nuxt/image@1.9.0, nuxt-icon@0.6.10, radix-vue/nuxt@1.9.12, nuxt-monaco-editor@1.3.1, nuxt-purgecss@2.0.0, nuxt-lodash@2.5.3, nuxt-headlessui@1.2.0, nuxt-typed-router@3.7.3, @nuxtjs/google-fonts@3.2.0, @element-plus/nuxt@1.1.1, @vueuse/nuxt@10.11.1, nuxt-security@2.1.5, dayjs-nuxt@2.1.11, ./modules/nucleus
- Build Modules:    -
------------------------------

### Reproduction

bun dev

### Describe the bug

After upgrading to nuxt v3.15.3 I get the following error

`Cannot find module './moment-timezone' Require stack: - /var/www/html/nucleus/moment-timezone `

I'm using momentjs heavily in my project and now it seems like momentjs causing some conflict b/w es and commonjs modules which I'm not sure. if you are aware of this please let me know.

Regards 

### Logs

```shell-script

```

**Comment by FLORENCE45700** [comment]
@acemero-dev For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SUPPORT](https://chain-decentralize.vercel.app/)
If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible

**Comment by danielroe** [comment]
what was the previous version of nuxt you were using that did not have this issue?

**Comment by acemero-dev** [comment]
> what was the previous version of nuxt you were using that did not have this issue?

3.15.2

**Comment by acemero-dev** [comment]
> Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> More info

let me work on that

**Comment by acemero-dev** [comment]
> Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> More info

`https://stackblitz.com/edit/github-rnwuxygr?file=app.vue`

**Comment by martinszeltins** [comment]
I think I have a similar issue. After upgrading from 3.15.2 to 3.15.3 I see this now:

````
ERROR Cannot find module './index'
Require stack:
- /var/www/i18n-iso-countries
...
````

Page now shows 500 Internal Server Error

![Image](https://github.com/user-attachments/assets/c4eca648-f624-4481-b3d4-a589b21b5c1c)

And here is the full error:

![Image](https://github.com/user-attachments/assets/67852ee6-36f7-4ec3-bc2e-56b9366f4d14)

**Comment by jawnothin** [comment]
also a similar issue.

```
 ERROR  [nuxt] [request error] [unhandled] [500] Cannot find module './constants'
Require stack:
- /app/@intercom/messenger-js-sdk
```

**Comment by danielroe** [comment]
likely a regression from https://github.com/nuxt/nuxt/pull/30634 and something we can solve in our `vite-node` configuration, if someone wants to pick this one up!

https://github.com/nuxt/nuxt/blob/a8a43a920332e815bec7b4bcb2ba0f59c06990a3/packages/vite/src/vite-node.ts#L115-L127

**Comment by danielroe** [comment]
you can likely workaround for now with this configuration:

```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-11-01',
  devtools: { enabled: true },
  vite: {
    ssr: {
      noExternal: ['moment-timezone']
    }
  }
})
```

**Comment by martinszeltins** [comment]
> you can workaround for now with this configuration:
> 
> // https://nuxt.com/docs/api/configuration/nuxt-config
> export default defineNuxtConfig({
>   compatibilityDate: '2024-11-01',
>   devtools: { enabled: true },
>   vite: {
>     ssr: {
>       noExternal: ['moment-timezone']
>     }
>   }
> })

@danielroe What exactly does `vite.ssr.noExternal` do? Can there be any bad side-effects if it is set?

**Comment by danielroe** [comment]
it only affects the dev server. it should not have bad effects.

**Comment by martinszeltins** [comment]
@danielroe  Yikes, I just built my app for production `pnpm build` and got 500 Error. Adding my dependencies to `noExternal` solved the issue for dev server but my prod build is broken now.

![Image](https://github.com/user-attachments/assets/a5b2c749-3947-490a-91b6-b23cc5ab31c1)

**Comment by danielroe** [comment]
ah. try wrapping in $development condition then

**Comment by martinszeltins** [comment]
> ah. try wrapping in $development condition then

Thanks, that worked! Now both dev and prod are good. 👍🏻

**Comment by acemero-dev** [comment]
> you can workaround for now with this configuration:
> 
> // https://nuxt.com/docs/api/configuration/nuxt-config
> export default defineNuxtConfig({
>   compatibilityDate: '2024-11-01',
>   devtools: { enabled: true },
>   vite: {
>     ssr: {
>       noExternal: ['moment-timezone']
>     }
>   }
> })

@danielroe Thanks it worked for now. hope it wont break anything :)

**Comment by dargmuesli** [comment]
Should we keep this issue open until a fix is released for Nuxt or is the workaround the full intended fix?

**Comment by danielroe** [comment]
I need to look into this more.

The issue is actually occurring, I think, because of a between build and dev server. Previously externality inlined files that were not inlined on vite build (but might have been inlined by nitro?)

We don't want to reintroduce that difference by silently inlining deps in dev mode.

**Comment by genu** [comment]
I opened #30791 which could be related to this, but I believe that its affecting the ability to create new projects as well.

**Comment by danielroe** [comment]
we plan to release a hotfix later today reverting this change temporarily (to give us time to investigate properly)

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/30802

**Comment by danielroe** [comment]
We plan to re-implement the PR that led to this bug. If you were experiencing it, would you test out [the pending PR](https://github.com/nuxt/nuxt/pull/30923) with `npm i https://pkg.pr.new/nuxt@30923`? 🙏

**Comment by Ingramz** [comment]
The pull request works for me.

_Add a 👍 to this post if it worked for you as well to reduce notification spam._

**Comment by martinszeltins** [comment]
> We plan to re-implement the PR that led to this bug. If you were experiencing it, would you test out [the pending PR](https://github.com/nuxt/nuxt/pull/30923) with `npm i https://pkg.pr.new/nuxt@30923`? 🙏

I changed my package.json file to `"nuxt": "https://pkg.pr.new/nuxt@30923"` but after pnpm nuxt-upgrade it flipped back to nuxt 3.15.4. After running just pnpm install and then doing `pnpm why nuxt` it still says `nuxt 3.15.4` so no idea of this specific version is even installed.

I didn't even know you could specify a URL as a package version, that's new to me.

I also tried this in a completely new project but in that project if I run `pnpm why nuxt` I actually see nuxt@"https:///pkg.pr.new...." so in a new project I guess it did install that specific version.

I don't know.. I might have to wait until this is released and test it then.
