### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/unstorage/drivers/overlay.mjs' imported from /var/task/index.mjs

### ISSUE THREAD

**Issue by TangsWang** [nuxt/nuxt#22553]
### Environment

when i upgrade to 3.6.5 to vercel, error: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/unstorage/drivers/overlay.mjs' imported from /var/task/index.mjs

### Reproduction
nuxt: 3.5.0 -> 3.6.5

everything is ok, on 3.5.0,

i used nitro { storage { dirver: 'memory' } } in nuxt.config.ts.

when i upgrade nuxt to 3.6.5,  on my local nodejs, is ok, but when i deploy to vercel, there was an error: [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/unstorage/drivers/memory.mjs' 

then i drop  nitro { storage { dirver: 'memory' } } , but it not work, there was another error: 
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/unstorage/drivers/overlay.mjs' imported from /var/task/index.mjs

### Describe the bug

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/unstorage/drivers/overlay.mjs' imported from /var/task/index.mjs

**Comment by TangsWang** [comment]
> Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> 
> More info

Reproduction
nuxt: 3.5.0 -> 3.6.5

everything is ok, on 3.5.0,

i used nitro { storage { dirver: 'memory' } } in nuxt.config.ts.

when i upgrade nuxt to 3.6.5, on my local nodejs, is ok, but when i deploy to vercel, there was an error: [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/unstorage/drivers/memory.mjs'

then i drop nitro { storage { dirver: 'memory' } } , but it not work, there was another error:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/unstorage/drivers/overlay.mjs' imported from /var/task/index.mjs

**Comment by TangsWang** [comment]
@danielroe  seems like https://github.com/nuxt/nuxt/issues/19919,  i don't know how to fix that, please help.

**Comment by TangsWang** [comment]
rm -rf node_modules
rm yarn.lock
yarn install

ok, thanks, @danielroe , i will close this.
