### ISSUE TITLE
useAsyncData/useFetch types do not reflect pick changes anymore

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt#25443]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-issues-25443

```vue
<script setup lang="ts">
const { data } = useAsyncData<{ data: { test: 1 } }>(
  'key',
  async (): Promise<any> => {
    return { data: { test: 1 } };
  },
  {
    pick: ['data'],
  }
);

const test = computed(() => data.value?.test);
</script>
<template>
  <div>
    {{ test }}
  </div>
</template>
```

Typcheck fails with `app.vue:12:41 - error TS2339: Property 'test' does not exist on type '{ data: { test: 1; }; }'.`

### Describe the bug

useFetch/useAsyncData should augment the provided type via generic when pick or transform is present.

**Comment by lmc3s3f0r** [comment]
Hi @manniL . I'm the guy who wrote the comment in YouTube about this issue. Thanks for taking the time to report this issue. I have like 68 error messages like this in my project since I updated from 3.8.2 to 3.9.3 and have no clue on how to get rid of them ^_^U

**Comment by happy-turtle** [comment]
I am not 100% sure if this applies to this issue. But I was able to resolve type errors in our project by explicitly pinning `"vue": "3.4.15"` after upgrading Nuxt to 3.9.x.

**Comment by danielroe** [comment]
This appears to be an issue just with `pick` as transform works fine (FWIW):

```ts
const { data } = useAsyncData(() => Promise.resolve({ data: { test: 1 } }), {
  pick: ['data'],
  // transform: data => data.data,
})
const test = computed(() => data.value?.test)
```

Looking to reproduce, this code (with `pick`) has a type error all the way back to at least v3.6.0 in the Nuxt playground.

**Comment by manniL** [comment]
@danielroe Attached a repro (that I wanted to put there before, sorry) also showing transform issues I think.

**Comment by lmc3s3f0r** [comment]
Would there be no way of having the useFetch return a globalThis.Ref<TYPE> (without using transform or pick) instead of Ref<TYPE> like before?

**Comment by danielroe** [comment]
This isn't actually a bug. (It got us all!) `pick` doesn't return _only_ that key, it just restricts the keys of an object to the keys passed in the array. (That's why it's an array, not a single string.)
