### ISSUE TITLE
Error 500 Cannot find module after upgrading from Nuxt 3.6.5

### ISSUE THREAD

**Issue by rfried** [nuxt/nuxt#24064]
**Edited to add negative results from a transpile solution attempt, thanks for the suggestion gavin!

### Environment

Nuxt project info: 

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Broken in 3.8.0: https://stackblitz.com/edit/nuxt-starter-39zg7i

Broken in 3.8.0 with transpile: https://stackblitz.com/edit/nuxt-starter-qtawiw?file=nuxt.config.ts

Working in 3.6.5: https://stackblitz.com/edit/nuxt-starter-nkvylc

### Describe the bug

I am upgrading from Nuxt 3.6.5 to Nuxt 3.8.0 and one of the fundamental dependencies of my site, paperjs, can no longer load. I have looked through https://nuxt.com/docs/guide/concepts/esm and I'm afraid that my understanding of the nuances of libraries is not to task here. This library I require is an older module, looks to be a CommonJS style, and something between 3.6.5 and 3.8.0 has broken the ability for this module to load relative files using 'require'. Technically I noticed this broke between 3.6.5 and 3.7 and have been holding off upgrading but I cannot do so any longer.

I looked through the open and closed issues and saw a few mentions of nitro traceInstances and that didn't resolve my issue. I also attempted the transpiling advice found in the esm explainer but the library I'm using doesn't work well with that as it's missing a default export.

I'm a bit stuck. Can I get a nudge towards the right answer or a solution to this issue?

**Comment by gavin667** [comment]
Hi @rfried we encountered something similar with the `@typescript/embed` package yesterday as it is also currently exposed only as a CommonJS module. We are on Nuxt `3.7.0`.

To get around this we added the package to the transpile array in Nuxt config like so:

```
build: {
  transpile: ['typescript/embed']
}
```

_Note in the transpile array there is no `@` before `typescript/embed`_

Hoping this might be of help? 🤞

**Comment by rfried** [comment]
hey @gavin667, thanks for your response :) 
I forgot to mention I had tried this and my understanding of modules failed to produce an answer as well. When I transpile paperjs in the nuxt.config.ts it still errors but differently:
https://stackblitz.com/edit/nuxt-starter-qtawiw?file=nuxt.config.ts

The error is on the browser console (instead of Nuxt's error page):
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/paper/dist/paper-full.js?v=4afdcdb7' does not provide an export named 'default' (at app.vue:11:8)

**Comment by rfried** [comment]
@danielroe when reviewing the documentation about modules I saw your generous offer to help people if they have trouble with modules as a result of recent changes. Indeed I have already worked through all of the import -> import type migrations that were introduced recently but cannot figure out how to get past this critical issue with the paperJS module.

* Do you know what changed between 3.6.5 and 3.7+ that would have impacted module resolution in this way?
* Do you know how to work around the issue with a configuration or code change without needing to upstream a fix to paperJS?
* If possible can you show the fix in a fork of one of my minimal reproduction environments?

Many thanks for your consideration

**Comment by danielroe** [comment]
@rfried I think this is likely a change in Vite. We upgraded it from v4.3 -> v4.4 [here](https://github.com/nuxt/nuxt/pull/21979).

**Comment by danielroe** [comment]
The solution here is to add `paper` to Vite's optimizeDeps array (see [docs](https://vitejs.dev/config/dep-optimization-options.html)):

https://stackblitz.com/edit/nuxt-starter-5tjcbq?file=package.json,app.vue,nuxt.config.ts,types.ts
