### ISSUE TITLE
"_interopRequireDefault2 is not a function" with 3.13.2

### ISSUE THREAD

**Issue by robmoredev** [nuxt/nuxt#29674]
Since updating nuxt from 3.13.1 to 3.13.2 I am now having an issue in one of my components when I import a library called [Jexl](https://github.com/TomFrost/Jexl) and try to initialize it I am seeing the following error:

_interopRequireDefault2 is not a function 

I am guessing this is related to this particular update. Is there a workaround for this? I noticed in https://github.com/nuxt/nuxt/releases/tag/v3.13.2  a comment:
"nuxt: Remove interop default for dynamic components (https://github.com/nuxt/nuxt/pull/28912)" 

which is maybe affecting my code?

Thanks!

**Comment by mattmoredev** [comment]
Repo here:

https://stackblitz.com/edit/github-7qj3e5?file=app.vue

**Comment by jgmdigital** [comment]
We are having the same issue when using typesense-instantsearch-adapter:

https://www.npmjs.com/package/typesense-instantsearch-adapter

We have had to rollback to 3.13.1 for the timebeing until a fix or workaround is confirmed.

Any advice would be appreciated, thank you.

**Comment by danielroe** [comment]
(This is unlikely related to that commit, which only affected importing Vue components.)

**Comment by mattmoredev** [comment]
> (This is unlikely related to that commit, which only affected importing Vue components.)

Any other idea why the latest Nuxt update might be causing these issues? The reason I thought it was this specific commit is because all versions of Nuxt prior to 3.13.2 worked fine and the 3rd party library I'm using ([Jexl](https://github.com/TomFrost/Jexl)) hasn't been updated in 3 years. I'm not entirely sure what was changed from nuxt 3.12.1 to 3.12.2 so when I saw in the release notes "remove interop default"  and looked very similar to the error I'm seeing now "_interopRequireDefault2 is not a function" I assumed the two were related.

Do you have any other insights or ideas as to what changed in the last Nuxt release that could be causing this issue? Any recommendations or workarounds I could try (other than scrapping Jexl and recoding that portion of  my project with another library)?

**Comment by lehuuphuc** [comment]
I have the same issue. 
I am using package vue-froala-wysiwyg. It works fine with Nuxt 3.13.1.
For Nuxt version after 3.13.1, I am getting error "_interopRequireDefault2 is not a function".

**Comment by lehuuphuc** [comment]
I change the package a bit like this and it works. Hope this can help you in investigating the issue.
![Image](https://github.com/user-attachments/assets/a31fdb53-affc-49f2-8dea-e37249e33144)

**Comment by HelloChrisBrown** [comment]
Seeing the same for vue-api-query.

**Comment by bobrov-site** [comment]
I have same error in sidebase/nuxt-auth using next-auth module

**Comment by maxt91** [comment]
Im facing a ton of issues even with the latest Nuxt version (3.15.3). Lodash no longer works when importing in this fashion "import cloneDeep from 'lodash/cloneDeep'" and has to be changed to "import {cloneDeep} from 'lodash'". Just like @lehuuphuc  mentioned  some months ago froala is broken all together and was forced to revert to 3.13.1.

**Comment by HelloChrisBrown** [comment]
> [@maxt91](https://github.com/maxt91) the latest release is now v3.15.4 - would you check if that makes any difference?

Still seeing the same error with  vue-api-query.

```
vue-api-query.js?v=83586508:3191 Uncaught TypeError: _interopRequireDefault2 is not a function
    at node_modules/vue-api-query/build/Model.js (vue-api-query.js?v=83586508:3191:28)
    at __require (chunk-DZZM6G22.js?v=83586508:9:50)
    at node_modules/vue-api-query/build/index.js (vue-api-query.js?v=83586508:3760:42)
    at __require (chunk-DZZM6G22.js?v=83586508:9:50)
    at vue-api-query.js?v=83586508:3763:16
```

**Comment by maxt91** [comment]
> [@maxt91](https://github.com/maxt91) the latest release is now v3.15.4 - would you check if that makes any difference?

hey daniel,
Yes same results with latest version ( 3.15.4 ) as well . Until its fixed we just had to lock our nuxt version to 3.13.1

**Comment by gabrielstuff** [comment]
> We are having the same issue when using typesense-instantsearch-adapter:
> 
> https://www.npmjs.com/package/typesense-instantsearch-adapter
> 
> We have had to rollback to 3.13.1 for the timebeing until a fix or workaround is confirmed.
> 
> Any advice would be appreciated, thank you.

Got the same issue here. Maybe it is related to the `vue-instantsearch` that you might use in combination with `typesense-instantsearch-adapter` 

Pining nuxt to `3.13.1` did help and I don't have the `_interopRequireDefault2 is not a function`. 

I've try to update to `3.15.4` and as soon as this two line show in the log, the app crashes:

```
[5:22:54 PM] ℹ ✨ new dependencies optimized: typesense
[5:22:54 PM] ℹ ✨ optimized dependencies changed. reloading
[5:22:57 PM] ℹ ✨ new dependencies optimized: typesense-instantsearch-adapter
[5:22:57 PM] ℹ ✨ optimized dependencies changed. reloading
```

So for now going back to `3.13.1`

**Comment by wtagain** [comment]
Same issue with nuxt@3.15.4 @danielroe

**Comment by danielroe** [comment]
This is probably not a Nuxt issue. Possibly `esbuild` or `vite` related - this is occurring in the vite dependency optimiser and I think it's likely because of the upgrade to vite v6.

**Comment by ericcholis** [comment]
@gabrielstuff I found this on the typesense-instatnsearch-adapter 

> Resolved with :
> 
> ```
>  // nuxt.config.js
>   alias: {
>     'typesense-instantsearch-adapter': 'typesense-instantsearch-adapter/src/TypesenseInstantsearchAdapter.js',
>   },
> ```

https://github.com/typesense/typesense-instantsearch-adapter/issues/227#issuecomment-2563681371

**Comment by gabrielstuff** [comment]
Going to update to nuxt `3.16` and see if it works. thanks @ericcholis for your feedback

**Comment by HelloChrisBrown** [comment]
I can confirm that `3.16` has fixed the issue for me using vue-api-query.
