### PR TITLE
fix(nuxt): avoid app config declaration conflicts

### LINKED ISSUE #35996: 4.5.1: app.config-declared component variant no longer type-checks (TS2322) — works on 4.5.0, still broken on 4.5.2
### Environment

- `nuxt`: 4.5.0 (working) → 4.5.1 / 4.5.2 (broken)
- `@nuxt/ui`: 4.10.0 (unchanged across the bump — ruled out as cause, see below)
- `vue-tsc` via `nuxt typecheck`
- App config declares a custom Nuxt UI variant, e.g.:

```ts
// app.config.ts
export default defineAppConfig({
  ui: {
    formField: {
      variants: {
        orientation: {
          action: 'flex items-center justify-between gap-4',
        },
      },
    },
  },
})
```

### Bug report

On `nuxt@4.5.0`, a template usage of the custom variant type-checks fine:

```vue
<UFormField orientation="action">...</UFormField>
```

On `nuxt@4.5.1` and `4.5.2`, the identical file/config, unchanged, fails `vue-tsc` with:

```
error TS2322: Type '"action"' is not assignable to type '"vertical" | "horizontal" | undefined'.
```

Runtime is unaffected — only the generated component prop type stops including the app.config-declared variant key.

### Isolation

- Two CI runs on the same commit range, ~4 minutes apart, touching neither the `.vue` file nor `app.config.ts`: `nuxt@4.5.0` green, `nuxt@4.5.1` red with the above error.
- `@nuxt/ui` is pinned at `4.10.0` in both runs (unchanged) — this rules out https://github.com/nuxt/ui/issues/6524 (a related-looking but distinct regression in `@nuxt/ui` itself, already fixed there via nuxt/ui#6531 well before 4.10.0).
- Locally re-verified against `nuxt@4.5.2` (latest as of writing): identical 2 errors, same lines. 4.5.2's changelog has no entries touching tsconfig/app-config type generation, consistent with this.
- Best current suspect (unconfirmed): https://github.com/nuxt/nuxt/pull/35673 ("Don't reference app config sources in shared and node tsconfigs"), the only app-config/type-generation-adjacent change in the 4.5.1 changelog. The PR's own description states no regression is expected for app-context files, so this may point elsewhere in the type-gen pipeline — flagging as the most likely lead, not a confirmed cause.

### Reproduction

1. `npx nuxi@latest init repro && cd repro`
2. Install `@nuxt/ui`, add a custom `formField.variants.orientation` key to `app.config.ts` as above.
3. Use `<UFormField orientation="action">` in any page.
4. `nuxt typecheck` on `nuxt@4.5.0` → passes.
5. Bump to `nuxt@4.5.1` (or `4.5.2`) → `nuxt typecheck` fails with TS2322 on the same line.

Happy to provide a minimal repro repo if useful.

### PR DESCRIPTION
**Pull request by oritwoen**
### 🔗 Linked issue

resolves #35996

### 📚 Description

The app and shared type contexts generated different declarations for the same `AppConfig` interface. With `skipLibCheck` enabled, TypeScript silently used whichever declaration was loaded first, so values from `app.config.ts` could disappear from component types.

This introduces a separate `SharedAppConfig` type for shared and server contexts, leaving `AppConfig` with a single app-specific declaration. The regression test compiles the generated declarations in both load orders and verifies the app and shared type boundaries.

### CODE REVIEW

**Comment by harlan-zw** [comment]
### 🤖 REVIEW PAUSED

> Harlan GitHub Agent posted this automated comment. [AI open source policy](https://harlanzw.com/blog/ai-in-open-source).

This pull request is from an outside contributor. Add the `harlan-agent-review` label to approve automated review and verified repairs for head commit `2a086441a46e`.

**Review by danielroe — APPROVED** [review]
❤️

File: packages/nuxt/test/templates.test.ts [hunk 1]
```diff
@@ -39,6 +42,91 @@ describe('appConfigTemplate', () => {
   })
 })
 
+describe('app config declaration templates', () => {
```
Comment (danielroe) [inline packages/nuxt/test/templates.test.ts]: this is a meaningless test

Comment (oritwoen) [reply packages/nuxt/test/templates.test.ts]: 😳, it was supposed to check regression but it was extremely overcomplicated, I push a new commit with the simplest test

Comment (danielroe) [reply packages/nuxt/test/templates.test.ts]: sorry for the strong words - I didn't mean it quite so negatively 😆
