### ISSUE TITLE
Nuxt 3.5.1 can not start dev, upgraded from 3.4.3

### ISSUE THREAD

**Issue by lpfy** [nuxt/nuxt#21069]
### Environment

- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      app, css, modules, ssr, lodash, pinia, build, typescript, devtools
- Runtime Modules:  nuxt-lodash@2.4.1, @nuxt/devtools@0.5.5, @pinia/nuxt@0.4.11, @nuxtjs/critters@0.4.0
- Build Modules:    -

### Reproduction

yarn dev

### Describe the bug

Cannot start nuxt:  Cannot find module '../doc/directives.js'

It seems the problem is related to package 'unplugin-vue-router' 0.6.4, once downgraded back to 3.4.3, everything is working properly.

![image](https://github.com/nuxt/nuxt/assets/4684417/7eacedef-15ff-45d5-8036-b6863517349c)

**Comment by LorenzoRottigni** [comment]
I also upgraded to 3.5.1 from 3.3 today and receiving tons of errors... i opened a discussion if it might help you: https://github.com/nuxt/nuxt/discussions/21080

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by anjali89r** [comment]
Getting this error after upgrading from 3.3.0 to 3.5.2
``` sh
[7:52:22 PM]  ERROR  Failed to resolve import "#components" from "virtual:nuxt:/Users/user/Documents/blog/test/.nuxt/components.plugin.mjs". Does the file exist?
```
Observed the same issue with 3.5.0 as well

**Comment by 171h** [comment]
> +1 In my case, it pending without any reporting-errors all the way. It will be ok just when i reduce to v3.5.0

In my case, v3.5.2 will be ok.

**Comment by LorenzoRottigni** [comment]
> Getting this error after upgrading from 3.3.0 to 3.5.2
> 
> ``` sh
> 
> [7:52:22 PM]  ERROR  Failed to resolve import "#components" from "virtual:nuxt:/Users/user/Documents/blog/test/.nuxt/components.plugin.mjs". Does the file exist?
> 
> ```
> 
> Observed the same issue with 3.5.0 as well 


I have a similar issue, would you give a look to my discussion? https://github.com/nuxt/nuxt/discussions/21080

**Comment by danielroe** [comment]
I cannot reproduce the issue on Windows by following these steps:

```sh
npx nuxi@latest init nuxt-test
cd nuxt-test
yarn
yarn dev
```

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/19841.
