### ISSUE TITLE
Error after upgrading to 3.6.3

### ISSUE THREAD

**Issue by bitbytebit1** [nuxt/nuxt#22156]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.16.0
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      telemetry, sourcemap, app, runtimeConfig, nitro, css, vite, modules, cors, i18n, build, devtools, imports, typescript
- Runtime Modules:  @vueuse/nuxt@10.2.1, nuxt-purgecss@2.0.0, @nuxtjs/i18n@8.0.0-beta.13-28155649.2e108fa, @pinia/nuxt@0.4.11
- Build Modules:    -
------------------------------

### Reproduction

Add this to your nuxt.config.js

```  
typescript: {
    tsConfig: {
      compilerOptions: {
        moduleResolution: 'bundler'
      }
    }
  }
```

### Describe the bug

The following error is thrown

```
[7:40:51 PM]  ERROR  Cannot start nuxt:  nuxt.options.typescript?.tsConfig?.compilerOptions?.moduleResolution?.toLowercase is not a function

  at initNitro (node_modules/nuxt/dist/index.mjs:2347:163)
  at initNuxt (node_modules/nuxt/dist/index.mjs:3264:9)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:205:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:249:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
  ```

### Additional context

Worked fine in 3.6.2

**Comment by bitbytebit1** [comment]
Fixed by removing the snippet from the config

**Comment by nengine** [comment]
Got the error below with npm install pinia @pinia/nuxt on Nuxt 3.6.3

```txt
While resolving: nuxt-app@undefined
Found: vue@3.3.4
node_modules/vue
  peer vue@"^3.3.4" from @nuxt/vite-builder@3.6.3
  node_modules/@nuxt/vite-builder
    @nuxt/vite-builder@"3.6.3" from nuxt@3.6.3
    node_modules/nuxt
      peer nuxt@"^3.6.1" from @nuxt/devtools@0.6.7
      node_modules/@nuxt/devtools
        dev @nuxt/devtools@"latest" from the root project
      peer nuxt@"^3.6.1" from @nuxt/devtools-kit@0.6.7
      node_modules/@nuxt/devtools-kit
        @nuxt/devtools-kit@"0.6.7" from @nuxt/devtools@0.6.7
        node_modules/@nuxt/devtools
          dev @nuxt/devtools@"latest" from the root project
      dev nuxt@"^3.6.3" from the root project
  peer vue@">=2.7 || >=3" from @unhead/vue@1.1.32
  node_modules/@unhead/vue
    @unhead/vue@"^1.1.30" from nuxt@3.6.3
    node_modules/nuxt
      peer nuxt@"^3.6.1" from @nuxt/devtools@0.6.7
      node_modules/@nuxt/devtools
        dev @nuxt/devtools@"latest" from the root project
      peer nuxt@"^3.6.1" from @nuxt/devtools-kit@0.6.7
      node_modules/@nuxt/devtools-kit
        @nuxt/devtools-kit@"0.6.7" from @nuxt/devtools@0.6.7
        node_modules/@nuxt/devtools
          dev @nuxt/devtools@"latest" from the root project
      dev nuxt@"^3.6.3" from the root project
  peer vue@"^3.2.25" from @vitejs/plugin-vue@4.2.3
  node_modules/@vitejs/plugin-vue
    @vitejs/plugin-vue@"^4.2.3" from @nuxt/vite-builder@3.6.3
    node_modules/@nuxt/vite-builder
      @nuxt/vite-builder@"3.6.3" from nuxt@3.6.3
      node_modules/nuxt
        peer nuxt@"^3.6.1" from @nuxt/devtools@0.6.7
        node_modules/@nuxt/devtools
          dev @nuxt/devtools@"latest" from the root project
        peer nuxt@"^3.6.1" from @nuxt/devtools-kit@0.6.7
        node_modules/@nuxt/devtools-kit
          @nuxt/devtools-kit@"0.6.7" from @nuxt/devtools@0.6.7
          node_modules/@nuxt/devtools
            dev @nuxt/devtools@"latest" from the root project
        dev nuxt@"^3.6.3" from the root project
  peer vue@"^3.0.0" from @vitejs/plugin-vue-jsx@3.0.1
  node_modules/@vitejs/plugin-vue-jsx
    @vitejs/plugin-vue-jsx@"^3.0.1" from @nuxt/vite-builder@3.6.3
    node_modules/@nuxt/vite-builder
      @nuxt/vite-builder@"3.6.3" from nuxt@3.6.3
      node_modules/nuxt
        peer nuxt@"^3.6.1" from @nuxt/devtools@0.6.7
        node_modules/@nuxt/devtools
          dev @nuxt/devtools@"latest" from the root project
        peer nuxt@"^3.6.1" from @nuxt/devtools-kit@0.6.7
        node_modules/@nuxt/devtools-kit
          @nuxt/devtools-kit@"0.6.7" from @nuxt/devtools@0.6.7
          node_modules/@nuxt/devtools
            dev @nuxt/devtools@"latest" from the root project
        dev nuxt@"^3.6.3" from the root project
  peerOptional vue@"^2.7.0 || ^3.2.25" from @vue-macros/common@1.5.0
  node_modules/@vue-macros/common
    @vue-macros/common@"^1.3.1" from unplugin-vue-router@0.6.4
    node_modules/unplugin-vue-router
      unplugin-vue-router@"^0.6.4" from nuxt@3.6.3
      node_modules/nuxt
        peer nuxt@"^3.6.1" from @nuxt/devtools@0.6.7
        node_modules/@nuxt/devtools
          dev @nuxt/devtools@"latest" from the root project
        peer nuxt@"^3.6.1" from @nuxt/devtools-kit@0.6.7
        node_modules/@nuxt/devtools-kit
          @nuxt/devtools-kit@"0.6.7" from @nuxt/devtools@0.6.7
          node_modules/@nuxt/devtools
            dev @nuxt/devtools@"latest" from the root project
        dev nuxt@"^3.6.3" from the root project
  peer vue@"3.3.4" from @vue/server-renderer@3.3.4
  node_modules/@vue/server-renderer
    @vue/server-renderer@"3.3.4" from vue@3.3.4
  vue@"^3.3.4" from nuxt@3.6.3
  node_modules/nuxt
    peer nuxt@"^3.6.1" from @nuxt/devtools@0.6.7
    node_modules/@nuxt/devtools
      dev @nuxt/devtools@"latest" from the root project
    peer nuxt@"^3.6.1" from @nuxt/devtools-kit@0.6.7
    node_modules/@nuxt/devtools-kit
      @nuxt/devtools-kit@"0.6.7" from @nuxt/devtools@0.6.7
      node_modules/@nuxt/devtools
        dev @nuxt/devtools@"latest" from the root project
    dev nuxt@"^3.6.3" from the root project
  peer vue@"^3.2.0" from vue-router@4.2.4
  node_modules/vue-router
    vue-router@"^4.2.4" from nuxt@3.6.3
    node_modules/nuxt
      peer nuxt@"^3.6.1" from @nuxt/devtools@0.6.7
      node_modules/@nuxt/devtools
        dev @nuxt/devtools@"latest" from the root project
      peer nuxt@"^3.6.1" from @nuxt/devtools-kit@0.6.7
      node_modules/@nuxt/devtools-kit
        @nuxt/devtools-kit@"0.6.7" from @nuxt/devtools@0.6.7
        node_modules/@nuxt/devtools
          dev @nuxt/devtools@"latest" from the root project
      dev nuxt@"^3.6.3" from the root project
    peerOptional vue-router@"^4.1.0" from unplugin-vue-router@0.6.4
    node_modules/unplugin-vue-router
      unplugin-vue-router@"^0.6.4" from nuxt@3.6.3
      node_modules/nuxt
        peer nuxt@"^3.6.1" from @nuxt/devtools@0.6.7
        node_modules/@nuxt/devtools
          dev @nuxt/devtools@"latest" from the root project
        peer nuxt@"^3.6.1" from @nuxt/devtools-kit@0.6.7
        node_modules/@nuxt/devtools-kit
          @nuxt/devtools-kit@"0.6.7" from @nuxt/devtools@0.6.7
          node_modules/@nuxt/devtools
            dev @nuxt/devtools@"latest" from the root project
        dev nuxt@"^3.6.3" from the root project

Could not resolve dependency:
pinia@"*" from the root project

Conflicting peer dependency: vue@2.6.14
node_modules/vue
  peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
  node_modules/@vue/composition-api
    peerOptional @vue/composition-api@"^1.4.0" from pinia@2.1.6
    node_modules/pinia
      pinia@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by jmarshall9120** [comment]
@nengine - I'm struggling with the same issue right now.  What was your resolutions?
