### ISSUE TITLE
Nuxt 4.4.2: $route and navigateTo no longer typed on component instance in templates

### ISSUE THREAD

**Issue by zlotnika** [nuxt/nuxt#34562]
### Environment

- Nuxt: 4.4.2 (works on 4.3.1)
- Vue: 3.5.30
- vue-router: 5.0.3
- Node: 22
- Package manager: bun

### Reproduction

Upgrade from `nuxt@4.3.1` to `nuxt@4.4.2` in any project that uses `$route` or `navigateTo` in `<script>` blocks (Options API style or `defineComponent`).

Run `nuxi typecheck`.

### Describe the bug

After upgrading from Nuxt 4.3.1 to 4.4.2, `nuxi typecheck` reports `$route` and `navigateTo` as missing from the component instance type in `.vue` files:

```
app/pages/records/index.vue(115,13): error TS2339: Property '$route' does not exist on type '{ ... 31 more ...; $nuxt: NuxtApp; }'.
app/pages/requests/index.vue(171,19): error TS2339: Property 'navigateTo' does not exist on type '{ ... 26 more ...; $nuxt: NuxtApp; }'.
```

The type includes `$nuxt: NuxtApp` but is missing `$route`, `$router`, and auto-imported utils like `navigateTo`.

Additionally, `colorMode` is no longer recognized on the Nuxt config type:

```
nuxt.config.ts(47,3): error TS2353: Object literal may only specify known properties, and 'colorMode' does not exist in type 'InputConfig<NuxtConfig, ConfigLayerMeta>'.
```

### Expected behavior

`$route`, `$router`, and Nuxt auto-imports (`navigateTo`, etc.) should be present on the component instance type, as they were in 4.3.1.

### Additional context

This affects every `.vue` file that references `$route` in the template or script — not a single-file issue. Rolling back to `nuxt@^4.3.1` resolves all errors.

**Comment by OrbisK** [comment]
can you try to upgrade to vue-router v5 (and/or dedupe your lockfile)

**Comment by zlotnika** [comment]
Closing — this is not a Nuxt regression. After deeper investigation:

**Root cause:** The bug is in `vue-tsc@3.0.2` / `@vue/language-core@3.0.2`, which drops `ComponentCustomProperties` augmentations from the component instance type. `vue-tsc@3.0.1` works correctly.

The issue was misdiagnosed as a Nuxt 4.4.2 regression because `vue-tsc` was upgraded at the same time as Nuxt. Rolling back to `nuxt@4.3.1` with `vue-tsc@3.0.2+` still fails; `nuxt@4.4.2` with `vue-tsc@3.0.1` passes.

**Workaround:** Pin `vue-tsc` to `3.0.1`.

Filed upstream: https://github.com/vuejs/language-tools/issues/5995

Tried vue-router v5 and deduping as suggested — neither resolves this since the root cause is in vue-tsc, not dependency resolution.

**Comment by zlotnika** [comment]
Correction to my earlier comment — after more testing, the vue-tsc regression was a red herring caused by stale `.nuxt` generated types in a git worktree. CI typecheck has been passing on main all along.

The original issue (Nuxt 4.4.2 types) may still be valid but I can no longer reproduce it reliably either. Will reopen if I can produce a clean reproduction.

**Comment by zlotnika** [comment]
Reopening — the regression IS confirmed. CI shows the failure when upgrading nuxt from 4.3.1 to 4.4.2. My earlier "not reproducible" comment was wrong — I was testing against main which already had the upgrade reverted.

**Comment by zlotnika** [comment]
**Minimal reproduction:** https://github.com/zlotnika/nuxt-34562-repro

Steps:
```bash
bun install
bun nuxi typecheck
```

The repro has just 2 tiny `.vue` files using `$route.path` in templates, with `nuxt@4.4.2` + 7 common modules (`@nuxt/eslint`, `@nuxt/icon`, `@nuxtjs/google-fonts`, `@nuxtjs/supabase`, `@vueuse/nuxt`, `@pinia/nuxt`, `dayjs-nuxt`).

Key finding: no single module triggers the bug — it requires a critical mass of modules registered together. Removing any one of the 4 modules (`@nuxt/eslint`, `@nuxt/icon`, `@nuxtjs/google-fonts`, `dayjs-nuxt`) makes it pass.

Also confirmed: `tsc --noEmit` passes fine — only `vue-tsc` fails. So the `ComponentCustomProperties` augmentations are structurally correct, but vue-tsc drops them from the component instance type when enough modules are present.

**Comment by spencerwalsh651-cmyk** [comment]
Thanks for the detailed report very helpful

**Comment by danielroe** [comment]
this is likely not a nuxt issue but probably caused by one of those modules augmenting the wrong vue module (e.g. `@vue/runtime-dom` rather than `vue`)

**Comment by zlotnika** [comment]
I've opened https://github.com/vuejs/language-tools/issues/5995 for this.

**Comment by posva** [comment]
Closing as this is not a Nuxt issue. As Daniel mentioned, one of the registered modules is likely augmenting the wrong Vue module (e.g. `@vue/runtime-dom` rather than `vue`), which causes `vue-tsc` to drop `ComponentCustomProperties` from the component instance type when enough modules are present.

Removing the modules confirms no typing errors with just Nuxt. I'd suggest bisecting which module causes the augmentation conflict and filing an issue on that module's repo.

Also tracked upstream: https://github.com/vuejs/language-tools/issues/5995
