### ISSUE TITLE
context.options.headers.get is not a function

### ISSUE THREAD

**Issue by SprayDev** [nuxt/nuxt#33604]
Im not sure if its related to Nuxt or more to unjs/ofetch issue
But after I updated nuxt to 4.2.0 version
I started to receive "context.options.headers.get is not a function" error when sending some fetch commands
I think it happen because when I create custom fetcher with $fetch.create() in "onRequest" interceptor I convert ctx.options.headers to an object like
`options.headers = {...options.headers, 'Content-Type': 'application/json'}`

Am I doing something wrong?
Because before I update to nuxt 4.2 this header conversion was working for a while in v3 and in v4 (till v4.2.0)

**Comment by TRIS-H** [comment]
I encountered a similar problem
After nuxt was upgraded from 4.0.1 to 4.1.0 or 4.2.0, a POST request was initiated using the $fetch method in the callback of the onMounted hook (the same should be true for GET requests, etc.), but the response was unsuccessful. An error message appears on the browser console: Failed to fetch,
However, this method will work normally until the version is updated to 4.1.0 or 4.2.0. It's unclear whether Nuxt or unjs/ofetch caused the problem

**Comment by SprayDev** [comment]
I've made small reproduction of this issue
https://stackblitz.com/edit/github-kbqwxvpo?file=app%2Fapp.vue
In App.vue file, I create new $fetch client and tries to send POST request with body and in console, you will see the error

**Comment by Priebojp** [comment]
I had the same problem. After rollback ofetch from version 1.5.0 to 1.4.1 the problem disappeared.

**Comment by SprayDev** [comment]
@Priebojp Strange. If we check package.json file there is dependency  "ofetch": "1.4.1" 
I think nuxt 4.2.0 using ofetch of version "1.4.1", shouldnt be a cause
But I think that its not really Nuxt problem, maybe this error triggered by ofetch
Lets wait for Dev`s response :)

**Comment by Flo0806** [comment]
Yes, this was the problem.. In the `Nuxt` repo (were I tried to reproduce the error) is `ofetch` 1.4.1 in use. But if you clone your repo and run pnpm install the newer 1.5.0 will be installed. `pnpm why ofetch`:

<img width="275" height="206" alt="Image" src="https://github.com/user-attachments/assets/5593e33e-2871-4fd0-a1a9-b40afc833881" />

I've create a issue in the `ofetch` repo.

**Comment by Umid-Berdiev** [comment]
Solution: Use new Headers to set the request headers in onRequest

```
onRequest({ options }) {
  const hdrs = new Headers(options.headers || {})
  const { locale } = useI18n()
  if (locale?.value) {
    hdrs.set("locale", locale.value)
  }
 
  options.headers = hdrs
}

```

**Comment by danielroe** [comment]
this is unlikely to be a nuxt issue - it's because you are converting headers to an object.

**Comment by danielroe** [comment]
oops, missed that @pi0 was investigating

**Comment by pi0** [comment]
ofetch [1.15.1](https://github.com/unjs/ofetch/releases/tag/v1.5.1) has a hotfix to normalize overriden `options.headers`.
