### ISSUE TITLE
[500] Cannot find module './internal/Observable' after updating from 3.15.2 to 3.15.3

### ISSUE THREAD

**Issue by gluharry** [nuxt/nuxt#30775]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.18.2`
- Nuxt Version:     `3.15.3`
- CLI Version:      `3.20.0`
- Nitro Version:    `2.10.4`
- Package Manager:  `npm@10.8.2`
- Builder:          `-`
- User Config:      `app`, `modules`, `runtimeConfig`, `css`, `components`, `vite`, `devtools`, `compatibilityDate`
- Runtime Modules:  `@nuxt/image@1.9.0`, `@gluhar/app@2.4.4`
- Build Modules:    `-`

### Reproduction

upgrade nuxt from 3.15.2 to 3.15.3

### Describe the bug

I just upgraded nuxt from 3.15.2 to 3.15.3 and when I do `npm run dev` I get:

[nuxt] [request error] [unhandled] [500] Cannot find module './internal/Observable'
Require stack:
- /Users/harryyaprakov/Work/rkmfn/rxjs

I have changed nothing else. 
When I revert back to 3.15.2 it gets immediately resolved.

Also, if I put 
build: {
    transpile: ["rxjs"],
  },
in my nuxt.config, the problem is resolved.

Thank you for the great work on Nuxt, its a joy using it and advocating for it! <3 

### Logs

```shell-script

```
