### ISSUE TITLE
Why do I get `error.value.statusCode` does not exists and how to solve?

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#24926]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.7.1
- Builder:          -
- User Config:      ssr, modules, ui, runtimeConfig, css, site, linkChecker, sitemap, colorMode, ogImage, vite, devtools
- Runtime Modules:  @nuxt/ui@2.11.1, @nuxtseo/module@2.0.0-beta.50
- Build Modules:    -
------------------------------

### Reproduction

- Create a nuxt project
- Create a composable like this one

```ts
export async function fetchRepoBySlug(slug: string) {
  const config = useRuntimeConfig()

  const data = await $fetch(`/repositories/${slug}`, {
    baseURL: config.public.apiBase,
  })

  const validatedData = myzod.object({
    data: myzod.object({
      name: myzod.string(),
      npmName: myzod.string().or(myzod.null()),
      stars: myzod.object({
        current: myzod.object({
          value: myzod.number(),
          fetchedAt: myzod.string(),
        }),
        previous: myzod.object({
          value: myzod.number(),
          fetchedAt: myzod.string(),
        }),
      }),
      downloads: myzod.object({
        current: myzod.object({
          value: myzod.number(),
          start: myzod.string(),
          end: myzod.string(),
        }),
        previous: myzod.object({
          value: myzod.number(),
          start: myzod.string(),
          end: myzod.string(),
        }),
      }),
      starsMetrics: myzod.array(myzod.object({
        value: myzod.number(),
        fetchedAt: myzod.string(),
      })),
      downloadsMetrics: myzod.array(myzod.object({
        value: myzod.number(),
        fetchedAt: myzod.string(),
      })),
    }),
  }).parse(data)

  return validatedData
}
```

And use it in a page

```ts
const route = useRoute()
const slug = route.params.slug as string
const { data: repo, error } = await useAsyncData(slug, () => fetchRepoBySlug(slug))

if (error.value) {
  // TODO: it's strange, why this happens?
  if (error.value.statusCode === 404) {
    throw createError({
      statusCode: 404,
      statusMessage: 'Repository not found',
      fatal: true,
    })
  }
}
```

### Describe the bug

Hello,

When using the useAsyncData, the type for the error is not a FetchError, which seems logic, but how to solve this since the value `statusCode` exists?

### Additional context

Full error

`Property 'statusCode' does not exist on type 'Error'.ts(2339)`

**Comment by manniL** [comment]
Can you provide a running reproduction please?

Something tells me that `error.value` is a union of various types and you have to narrow it down (because indeed, `Error` has no `statusCode` but `H3Error` has (checking e.g. via `isNuxtError`)

**Comment by Barbapapazes** [comment]
I'm trying to reproduce but I don't know why it's seems a little bit tricky.

Why the error could be an H3Error? How could it be related to H3?

**Comment by Barbapapazes** [comment]
Sometimes, it's a NuxtError, sometime a H3Error. Could I have some explanation on how TypeScript choose which type?

**Comment by Barbapapazes** [comment]
Types when everything if fine (`.nuxt/types/imports.d.ts`)

![image](https://github.com/nuxt/nuxt/assets/45267552/9e366b54-b125-460f-8adc-c51ef0417384)

When I got the error (same file)

![image](https://github.com/nuxt/nuxt/assets/45267552/9afbcd6c-cc5c-4338-a501-a8c4f3c246da)

**Comment by Barbapapazes** [comment]
With Nuxt@3.9.0

![image](https://github.com/nuxt/nuxt/assets/45267552/a717841f-7e80-497a-ac4f-a9b84bad11c5)

**Comment by Barbapapazes** [comment]
Okk, after retrying with nuxt@3.8.2, seems related to this version since it's working fine with nuxt@3.9.0.

I don't know why this happens and if it could happen again so I do not close this issue. Feel free to close it.

**Comment by danielroe** [comment]
Yes, we fixed the types in Nuxt v3.9.0 in https://github.com/nuxt/nuxt/pull/24396.
