### ISSUE TITLE
Build/Preview broken after switching to 3.3.2

### ISSUE THREAD

**Issue by sfxcode** [nuxt/nuxt#19919]
Seems to be a problem with latest unstorage build: 1.4.1

Latest version 3.3.1 (using unstorage 1.4.0) worked fine.

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/tom/projects/sfxcode/vue/nuxt3-primevue-starter/.output/server/node_modules/unstorage/drivers/overlay.mjs' imported from /Users/tom/projects/sfxcode/vue/nuxt3-primevue-starter/.output/server/index.mjs
```

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@7.30.3`
- Builder:          `vite`
- User Config:      `ssr`, `runtimeConfig`, `modules`, `content`, `unocss`, `primevue`, `css`, `build`, `sourcemap`
- Runtime Modules:  `@formkit/nuxt@0.16.4`, `@sfxcode/nuxt-primevue@1.0.5`, `@unocss/nuxt@0.50.6`, `@pinia/nuxt@0.4.7`, `@nuxt/content@2.5.2`, `@vueuse/nuxt@9.13.0`
- Build Modules:    `-`

**Comment by danielroe** [comment]
Would you try refreshing your lockfile?

cc: @pi0

**Comment by sfxcode** [comment]
Already have. Seems the unstorage 1.4.1 folder in output/node_modules don't have a driver directory.

<img width="353" alt="Bildschirm­foto 2023-03-25 um 17 40 11" src="https://user-images.githubusercontent.com/4506602/227730340-7a58a6d6-f773-4bb5-9c60-2b69947db346.png">

like in 1.4.0

<img width="267" alt="Bildschirm­foto 2023-03-25 um 17 42 48" src="https://user-images.githubusercontent.com/4506602/227730423-86c6579c-d941-4ea3-a456-511abfc2c590.png">

**Comment by danielroe** [comment]
I think the issue will be upstream in nitro in that case, as the published `unstorage@1.4.1` does have the directory: https://unpkg.com/browse/unstorage@1.4.1/.

Would you check your lockfile to see if there is more than one version installed?

**Comment by sfxcode** [comment]
@danielroe you are right, got a additional different (1.4.0) , so  build with nitro for 1.4.1 seems to fail. Added unstorage 1.4.1 in package to force 1.4.1, solved this problem, even after remveving it afterwards. 

Thank you, i will close tis issue,

Tom

**Comment by danielroe** [comment]
cc: @pi0 - likely an issue with hoisting.

**Comment by gumingWu** [comment]
> @danielroe you are right, got a additional different (1.4.0) , so build with nitro for 1.4.1 seems to fail. Added unstorage 1.4.1 in package to force 1.4.1, solved this problem, even after remveving it afterwards.
> 
> Thank you, i will close this issue,
> 
> Tom

Hi bro, I met the same problem like missing the `drivers` floder, would you teach me how to solve it? :)

I try to delete `pnpm-lock` and re-install, but it failed again.

![image](https://user-images.githubusercontent.com/24989299/228284881-18a54f58-14cc-4226-b9c3-7a3ded211834.png)

**Comment by mahapo** [comment]
Downgrade @nuxt/content to 2.5.1 and add   
```
"resolutions": {
    "unstorage": "1.4.1"
  }
  
```
  to package.json fix the issue
  https://github.com/nuxt/content/issues/2037

**Comment by Sailsnake-sites** [comment]
Simply nuking node_modules and yarn.lock -> run: yarn install -> commit and push - worked for me!

**Comment by arpadgabor** [comment]
Still seeing this error with Nuxt 3.6.1, unstorage 1.6.1, pnpm, with shamefully-hoist.

```
 Error - Cannot find module '/var/task/node_modules/unstorage/drivers/fs.mjs' imported from /var/task/server.mjs 
```

**Comment by memic84** [comment]
Same issues here, while upgraden to 3.6.1

**Comment by Aleksandr-Baranchuk** [comment]
For me, the following solved the problem:
rm -rf node_modules
rm yarn.lock 
yarn install

**Comment by hecktarzuli** [comment]
I'm running 3.6.5, and I'm still seeing the error @kamnog

**Comment by TangsWang** [comment]
> 

Same issues here, while upgrading to 3.6.5, yarn, on my local node is ok, but when deploy to vercel, there was errors you mentioned before.

some one help me?
