### ISSUE TITLE
defineEmits not typed properly on auto imported components after upgrading to 4.1.0

### ISSUE THREAD

**Issue by MikeBellika** [nuxt/nuxt#33134]
### Environment

- Operating System: `Darwin`
- Node Version:     `v22.17.0`
- Nuxt Version:     `4.1.0`
- CLI Version:      `3.28.0`
- Nitro Version:    `2.12.5`
- Package Manager:  `pnpm@9.15.4`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/MikeBellika/nuxt-defineemits-type-error

### Describe the bug

When auto importing components, it seems the emits aren't properly typed. The reproduction should show the problem pretty well and minimally but i'll add it here as well:

```vue
<script setup lang="ts">
// MyEmitter.vue
defineEmits<{ cool: [value: boolean] }>();
</script>
<template>
  <button @click="$emit('cool', true)">emit</button>
</template>
```

```vue
<script setup lang="ts">
// This component gives a type error, because it can't see the type of `e`
const hello = ref(false);
</script>
<template>
  <div>
    <MyEmitter @cool="(e) => (hello = e)" />
    <!--    Parameter 'e' implicitly has an 'any' type -->
    {{ hello }}
  </div>
</template>
```

```vue
<script setup lang="ts">
// No error when importing component explicitly.
import { MyEmitter } from "#components";
const hello = ref(false);
</script>
<template>
  <div>
    <MyEmitter @cool="(e) => (hello = e)" />
    {{ hello }}
  </div>
</template>
```

### Additional context

In our project this error occurred after upgrading to nuxt 4.1.0 from 4.0.0. However the error seems to still happen on 4.0.0 in the reproduction repo. Might be coming from a dependency of nuxt.

### Logs

```shell-script
app/components/AutoImported.vue:6:24 - error TS7006: Parameter 'e' implicitly has an 'any' type.

6     <MyEmitter @cool="(e) => (hello = e)" />
                         ~


Found 1 error.
```

**Comment by cernymatej** [comment]
This is most probably a volar / vue bug.

**Comment by danielroe** [comment]
I think this might have been resolved in https://github.com/nuxt/nuxt/pull/33122 - would you try the pkg.pr.new to confirm? 🙏

**Comment by MikeBellika** [comment]
> I think this might have been resolved in [#33122](https://github.com/nuxt/nuxt/pull/33122) - would you try the pkg.pr.new to confirm? 🙏

@danielroe Yes this works!
