### ISSUE TITLE
Project with local module crashes after updating to nuxt 3.5

### ISSUE THREAD

**Issue by SimonSimCity** [nuxt/nuxt#20912]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.5.0`
- Nitro Version:    `2.4.1`
- Package Manager:  `pnpm@8.5.1`
- Builder:          `vite`
- User Config:      `modules`, `runtimeConfig`, `i18n`, `imports`, `ssr`, `vite`, `app`
- Runtime Modules:  `nuxt-typed-router@3.2.0`, `@nuxt/devtools@0.4.1`, `./modules/figma2tailwind`, `@nuxtjs/tailwindcss@6.6.6`, `@nuxtjs/i18n@8.0.0-beta.10`, `@pinia/nuxt@0.4.9`
- Build Modules:    `-`

### Reproduction

1. Set up a new nuxt project - `npx nuxi init test-project`
2. Install the packages - `pnpm i`
3. Register a local module `./modules/testModule.ts`
4. Create a local module in the registered file
5. Run `pnpm i` again and watch it fail ...

For testing, my module (located in `./modules/testModule.ts`) looks like:
```ts
import { defineNuxtModule } from "@nuxt/kit";

export default defineNuxtModule({
  meta: {
    name: "testModule",
  },
  async setup(_, nuxt) {
    console.log("Successful 🎉")
  },
});
```

My `nuxt.config.ts` looks like:
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
    modules: ["./modules/testModule.ts"]
})
```

### Describe the bug

When running nuxt with a module on a relative path, it crashes. Inline-module definitions and package-names seem to work just fine.

Using local modules worked in nuxt 3.4 and is mentioned in the documentation: https://nuxt.com/docs/guide/concepts/modules

### Logs

```shell-script
> nuxt prepare

Nuxi 3.5.0                                                           10:54:42 AM

[10:54:45 AM]  ERROR  Error while requiring module ./modules/figma2tailwind: Error: Cannot find module 'modules/figma2tailwind'
Require stack:
- /Users/simon/Documents/myProject/index.js


 ERROR  Cannot find module 'modules/figma2tailwind'                  10:54:45 AM
Require stack:
- /Users/simon/Documents/myProject/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
  at Function.resolve (node:internal/modules/cjs/helpers:109:19)
  at Function._resolve [as resolve] (node_modules/.pnpm/jiti@1.18.2/node_modules/jiti/dist/jiti.js:1:241025)
  at resolveModule (node_modules/.pnpm/@nuxt+kit@3.5.0/node_modules/@nuxt/kit/dist/index.mjs:260:29)
  at requireModule (node_modules/.pnpm/@nuxt+kit@3.5.0/node_modules/@nuxt/kit/dist/index.mjs:270:24)
  at normalizeModule (node_modules/.pnpm/@nuxt+kit@3.5.0/node_modules/@nuxt/kit/dist/index.mjs:466:90)
  at async installModule (node_modules/.pnpm/@nuxt+kit@3.5.0/node_modules/@nuxt/kit/dist/index.mjs:439:41)
  at async initNuxt (node_modules/.pnpm/nuxt@3.5.0_@types+node@18.15.13_eslint@8.39.0_stylelint@15.5.0_typescript@4.9.5_vue-tsc@1.6.4/node_modules/nuxt/dist/index.mjs:2889:7)
  at async loadNuxt (node_modules/.pnpm/nuxt@3.5.0_@types+node@18.15.13_eslint@8.39.0_stylelint@15.5.0_typescript@4.9.5_vue-tsc@1.6.4/node_modules/nuxt/dist/index.mjs:2950:5)
  at async loadNuxt (node_modules/.pnpm/@nuxt+kit@3.4.3/node_modules/@nuxt/kit/dist/index.mjs:545:19)

 ELIFECYCLE  Command failed with exit code 1.
```
```

**Comment by Horlamedhey** [comment]
@SimonSimCity change 
`"./modules/testModule.ts"`
to
`"~/modules/testModule.ts"`

**Comment by SimonSimCity** [comment]
Well, in my project, the imported module is referenced by its directory, which is why I (after updating the path according to your changes) got the following error message:

```ts
 ERROR  Error while requiring module ~/modules/figma2tailwind: Error: EISDIR: illegal operation on a directory, read    12:23:37 PM


 ERROR  Cannot start nuxt:  EISDIR: illegal operation on a directory, read                                              12:23:37 PM

  at Object.readSync (node:fs:748:3)
  at tryReadSync (node:fs:448:20)
  at readFileSync (node:fs:494:19)
  at jiti (node_modules/.pnpm/jiti@1.18.2/node_modules/jiti/dist/jiti.js:1:244019)
  at requireModule (node_modules/.pnpm/@nuxt+kit@3.5.0/node_modules/@nuxt/kit/dist/index.mjs:274:26)
  at normalizeModule (node_modules/.pnpm/@nuxt+kit@3.5.0/node_modules/@nuxt/kit/dist/index.mjs:466:90)
  at async installModule (node_modules/.pnpm/@nuxt+kit@3.5.0/node_modules/@nuxt/kit/dist/index.mjs:439:41)
  at async initNuxt (node_modules/.pnpm/nuxt@3.5.0_@types+node@20.1.7_eslint@8.39.0_stylelint@15.5.0_typescript@5.0.4_vue-tsc@1.6.0/node_modules/nuxt/dist/index.mjs:2889:7)                                                                                 12:23:29 PM
  at async load (node_modules/.pnpm/nuxi@3.5.0/node_modules/nuxi/dist/chunks/dev.mjs:201:9)
  at async Object.invoke (node_modules/.pnpm/nuxi@3.5.0/node_modules/nuxi/dist/chunks/dev.mjs:245:5)
```

If this is how it should be, the docs need an update.

**Comment by Horlamedhey** [comment]
Yes, you're right... I only commented on the correction based on the module in your original question

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/20883.
