### ISSUE TITLE
Nuxt 3.16.x breaks hot reloading when using nuxt-mapbox

### ISSUE THREAD

**Issue by intuitiveminds** [nuxt/nuxt#31471]
### Environment

- Operating System: Darwin
- Node Version:     v22.14.0
- Nuxt Version:     3.16.1
- CLI Version:      3.23.1
- Nitro Version:    2.11.7
- Package Manager:  npm@11.2.0
- Builder:          -
- User Config:      compatibilityDate, devtools, modules
- Runtime Modules:  nuxt-mapbox@1.6.2
- Build Modules:    -

### Reproduction

Issue can be reproduced using this repository: https://github.com/intuitiveminds/nuxtmapbox

### Describe the bug

I am using nuxt-mapbox and upgraded to Nuxt 3.16.1 from Nuxt 3.15.4. With Nuxt 3.15.4 hot reloading during development works as expected, however with Nuxt 3.16.1 (and Nuxt 3.16.0 as well) I get an error when I do a code change after the page has been rendered in the browser:

```
runtime-core.esm-bundler.js:5823 Uncaught (in promise) TypeError: parentComponent.ctx.deactivate is not a function
    at unmount (runtime-core.esm-bundler.js:5823:27)
    at patch (runtime-core.esm-bundler.js:4651:7)
    at sharedContext.activate (runtime-core.esm-bundler.js:2565:7)
    at processComponent (runtime-core.esm-bundler.js:5174:29)
    at patch (runtime-core.esm-bundler.js:4700:11)
    at patchSuspense (runtime-core.esm-bundler.js:6981:7)
    at Object.process (runtime-core.esm-bundler.js:6779:7)
    at patch (runtime-core.esm-bundler.js:4725:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5406:9)
    at ReactiveEffect.run (reactivity.esm-bundler.js:225:19)
```

Note that I first thought it is similar to https://github.com/nuxt/nuxt/issues/31446 , but I am using a single root node. Once stripping down my app I discovered that if I remove the nuxt-mapbox module from nuxt.config.ts, hot reloading works as it should. Just including this module (even if not using any component in my app) breaks hot reloading. Since this worked in 3.15.4 I opened this bug here and not in the nuxt-mapbox repository.

### Logs

```shell-script

```

**Comment by vis97c** [comment]
Possible duplicate of https://github.com/nuxt/nuxt/issues/31446
