### ISSUE TITLE
Cannot run npm install with custom modules with Nuxt 3.5.0

### ISSUE THREAD

**Issue by mcrapts** [nuxt/nuxt#20883]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.0
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      modules
- Runtime Modules:  ./modules/myModule
- Build Modules:    -
------------------------------
```

### Reproduction

Run `npm install` in this sandbox: 
https://stackblitz.com/edit/github-s6insh?file=nuxt.config.ts

### Describe the bug

Running `npm install` with a custom module results in an error that the module cannot be found. I wasn't expecting an error. This previously worked fine with Nuxt 3.4.3.

```
ERROR  Error while requiring module ./modules/myModule: Error: Cannot find module 'modules/myModule'           5:15:13 PM
Require stack:
- /home/projects/github-s6insh/index.js


 ERROR  Cannot start nuxt:  Cannot find module 'modules/myModule'                                               5:15:13 PM
Require stack:                                                                                                  5:15:07 PM
- /home/projects/github-s6insh/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (https://githubs6insh-mmv3.w-corp.staticblitz.com/blitz.bdcb25d8.js:35:242305)
  at Function.resolve (https://githubs6insh-mmv3.w-corp.staticblitz.com/blitz.bdcb25d8.js:35:480406)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:241100)
  at resolveModule (file://node_modules/@nuxt/kit/dist/index.mjs:331:36)
  at requireModule (file://node_modules/@nuxt/kit/dist/index.mjs:341:24)
  at normalizeModule (file://node_modules/@nuxt/kit/dist/index.mjs:537:90)
  at async Module.installModule (file://node_modules/@nuxt/kit/dist/index.mjs:510:41)
  at async initNuxt (file://node_modules/nuxt/dist/index.mjs:2906:7)
  at async load (file://node_modules/nuxi/dist/chunks/dev.mjs:216:9)
  at async Object.invoke (file://node_modules/nuxi/dist/chunks/dev.mjs:260:5)
```

**Comment by danielroe** [comment]
Thank you. As a workaround, you can update to:

```
modules: ['~/modules/myModule/index'],
```

**Comment by mcrapts** [comment]
That also results in an error:
```
ERROR  Cannot find module 'modules/myModule/index'
Require stack:
- /home/projects/github-s6insh-eawouj/index.js
```

index.js indeed doesn't exist, it should be index.ts.

**Comment by danielroe** [comment]
You can see it working here: https://stackblitz.com/edit/github-s6insh-z11cqr?file=nuxt.config.ts

**Comment by mcrapts** [comment]
Ah, I see, I didn't add the `~` character.

**Comment by TinyLightBold** [comment]
I got this problem with yarn run build:

✔ Server built in 3788ms                                                                                                                                                                                                                                   13:41:35
✔ Generated public .output/public                                                                                                                                                                                                                    nitro 13:41:35
ℹ Building Nitro Server (preset: node-server)                                                                                                                                                                                                        nitro 13:41:35

 ERROR  Error: EISDIR: illegal operation on a directory, readlink 'D:\DEVELOPMENT\PROJECTS\projectX\node_modules\node-fetch-native\dist\polyfill.mjs'                                                                                       nitro 13:42:14  


undefined


 ERROR  EISDIR: illegal operation on a directory, readlink 'D:\DEVELOPMENT\PROJECTS\projectX\node_modules\node-fetch-native\dist\polyfill.mjs'                                                                                                    13:42:14

**Comment by danielroe** [comment]
@TinyLightBold I don't think that's the same issue. Could you create a new issue with a reproduction, please? 🙏

**Comment by TinyLightBold** [comment]
> 

I'll try to create one
