### ISSUE TITLE
__asyncHydrate is not a function

### ISSUE THREAD

**Issue by Tofandel** [nuxt/nuxt#28809]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.11.1
- Nuxt Version:     3.13.0
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

This is happening on any project with nuxt and vue 3.5.0 (released 1h ago)
Just `nuxt build` and `node .output/server/index.mjs` and visit the `localhost:3000`

### Describe the bug

When running `nuxt build` any page visit is not hydrated on the client, instead there is js error `__asyncHydrate` is not a function on NuxtRoot

### Additional context

Caused by commit https://github.com/vuejs/core/commit/d14a11c1cdcee88452f17ce97758743c863958f4

**Comment by danielroe** [comment]
You might need to update your lockfile to ensure you don't have mismatching versions of `vue` installed.

**Comment by Tofandel** [comment]
I checked, it's a clean upgrade, everything is in 3.5.0

<details>

    "node_modules/@vue/reactivity": {
      "version": "3.5.0",
      "resolved": "https://registry.npmjs.org/@vue/reactivity/-/reactivity-3.5.0.tgz",
      "integrity": "sha512-Ew3F5riP3B3ZDGjD3ZKb9uZylTTPSqt8hAf4sGbvbjrjDjrFb3Jm15Tk1/w7WwTE5GbQ2Qhwxx1moc9hr8A/OQ==",
      "dev": true,
      "dependencies": {
        "@vue/shared": "3.5.0"
      }
    },
    "node_modules/@vue/runtime-core": {
      "version": "3.5.0",
      "resolved": "https://registry.npmjs.org/@vue/runtime-core/-/runtime-core-3.5.0.tgz",
      "integrity": "sha512-mQyW0F9FaNRdt8ghkAs+BMG3iQ7LGgWKOpkzUzR5AI5swPNydHGL5hvVTqFaeMzwecF1g0c86H4yFQsSxJhH1w==",
      "dev": true,
      "dependencies": {
        "@vue/reactivity": "3.5.0",
        "@vue/shared": "3.5.0"
      }
    },
    "node_modules/@vue/runtime-dom": {
      "version": "3.5.0",
      "resolved": "https://registry.npmjs.org/@vue/runtime-dom/-/runtime-dom-3.5.0.tgz",
      "integrity": "sha512-NQQXjpdXgyYVJ2M56FJ+lSJgZiecgQ2HhxhnQBN95FymXegRNY/N2htI7vOTwpP75pfxhIeYOJ8mE8sW8KAW6A==",
      "dev": true,
      "dependencies": {
        "@vue/reactivity": "3.5.0",
        "@vue/runtime-core": "3.5.0",
        "@vue/shared": "3.5.0",
        "csstype": "^3.1.3"
      }
    },
    "node_modules/@vue/server-renderer": {
      "version": "3.5.0",
      "resolved": "https://registry.npmjs.org/@vue/server-renderer/-/server-renderer-3.5.0.tgz",
      "integrity": "sha512-HyDIFUg+l7L4PKrEnJlCYWHUOlm6NxZhmSxIefZ5MTYjkIPfDfkwhX7hqxAQHfgIAE1uLMLQZwuNR/ozI0NhZg==",
      "dev": true,
      "dependencies": {
        "@vue/compiler-ssr": "3.5.0",
        "@vue/shared": "3.5.0"
      },
      "peerDependencies": {
        "vue": "3.5.0"
      }
    },
    "node_modules/@vue/shared": {
      "version": "3.5.0",
      "resolved": "https://registry.npmjs.org/@vue/shared/-/shared-3.5.0.tgz",
      "integrity": "sha512-m9IgiteBpCkFaMNwCOBkFksA7z8QiKc30ooRuoXWUFRDu0mGyNPlFHmbncF0/Kra1RlX8QrmBbRaIxVvikaR0Q==",
      "dev": true
    },
<summary>
package-lock.json
</summary>
</details>

**Comment by Tofandel** [comment]
It's coming from vue3-lazy-hydration

https://github.com/freddy38510/vue3-lazy-hydration/issues/91

**Comment by Emili-HD** [comment]
I've the same problem. How did you solve it?

**Comment by Tofandel** [comment]
See linked issue, for now just pin vue to 3.4.41
