### ISSUE TITLE
vue-i18n not working with Nuxt 3.7

### ISSUE THREAD

**Issue by mcrapts** [nuxt/nuxt#23180]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.2
- CLI Version:      3.8.3
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, vite
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-hnz7et-dysose?file=nuxt.config.ts

### Describe the bug

It works in dev mode but not when you build the app.

1. Run `npm run build`
2. Run the build using `node .output/server/index.mjs`
3. Access the application using localhost:3000
4. Observe the following error:
`[nuxt] [request error] [unhandled] [500] Cannot find module '/home/projects/github-hnz7et-dysose/.output/server/chunks/dist/vue-i18n.runtime.mjs' imported from /home/projects/github-hnz7et-dysose/.output/server/chunks/app/server.mjs`

### Additional context

vue-i18n used to work with Nuxt 3.6 but not anymore with 3.7. Nonetheless, this might actually be an issue with vue-i18n and not Nuxt but I'm not sure how to get to the bottom of this issue.

**Comment by DanielRivers** [comment]
@mcrapts Your reproduction link doesn't show the error, is there a reason why you're not using the i18n module which wraps this? https://nuxt.com/modules/i18n

**Comment by mcrapts** [comment]
@DanielRivers did you run `npm run build && node .output/server/index.mjs`? It works in dev, but not when you build it.

I didn't use the i18n module because it's not in the instructions for vue-i18n. https://vue-i18n.intlify.dev/guide/integrations/nuxt3.html

**Comment by danielroe** [comment]
This seems like it might be an upstream issue with `vue-i18n` rather than Nuxt. Would you open an issue there instead?

**Comment by mcrapts** [comment]
Thanks, that does indeed seems to be a workaround. I will open an issue with `vue-i18n`!

**Comment by mcrapts** [comment]
The `vue-i18n` [docs](https://vue-i18n.intlify.dev/guide/integrations/nuxt3.html#optimize-with-intlify-unplugin-vue-i18n) have been updated, so this issue can be closed.
