### PR TITLE
fix(core): correctly use `toLowerCase` for possible `moduleResolution`

### LINKED ISSUE #22156: Error after upgrading to 3.6.3
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.16.0
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      telemetry, sourcemap, app, runtimeConfig, nitro, css, vite, modules, cors, i18n, build, devtools, imports, typescript
- Runtime Modules:  @vueuse/nuxt@10.2.1, nuxt-purgecss@2.0.0, @nuxtjs/i18n@8.0.0-beta.13-28155649.2e108fa, @pinia/nuxt@0.4.11
- Build Modules:    -
------------------------------

### Reproduction

Add this to your nuxt.config.js

```  
typescript: {
    tsConfig: {
      compilerOptions: {
        moduleResolution: 'bundler'
      }
    }
  }
```

### Describe the bug

The following error is thrown

```
[7:40:51 PM]  ERROR  Cannot start nuxt:  nuxt.options.typescript?.tsConfig?.compilerOptions?.moduleResolution?.toLowercase is not a function

  at initNitro (node_modules/nuxt/dist/index.mjs:2347:163)
  at initNuxt (node_modules/nuxt/dist/index.mjs:3264:9)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:205:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:249:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
  ```

### Additional context

Worked fine in 3.6.2

### Logs

_No response_

### PR DESCRIPTION
**Pull request by TheAlexLichter**
### 🔗 Linked issue

Resolves https://github.com/nuxt/nuxt/issues/22156

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Simple typo in `toLowercase` -> `toLowerCase`.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
Ouch. Thanks for the fix!
