### PR TITLE
feat: experimental config schema

### PR DESCRIPTION
**Pull request by pi0**
### 🔗 Linked issue

https://github.com/nuxt/nuxt/issues/15592

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Implementing custom config schema support (enabled using `experimental.configSchema: true`). Read more in #15592

TODO:
- [x] Port [nuxt-config-schema](https://github.com/nuxt-experiments/nuxt-config-schema) to the core
- [ ] ~Add docs to Going further > Config Schema + hooks~ (postpone to later PR)
- [x] Little bit of cleanups
- [x] Handle empty schema
- [x] `extendConfigSchema` kit utility
- [x] Watch for schema file changes in dev

### CODE REVIEW

**Review by atinux — APPROVED** [review]

**Comment by pi0** [comment]
Merging to try on edge

**Comment by burda-osowiecki** [comment]
It does not work :'(

I'm importing the appConfig dynamically based on process.env (in nuxt.config.ts)

After updating from 3.0.0 to 3.1.1
I'm getting errors from `vue-tsc` like `Property 'x' does not exist on type 'AppConfig' `

I was trying to declare `interface AppConfigInput` in `index.d.ts` like here
https://nuxt.com/docs/guide/directory-structure/app-config#manually-typing-app-config
I also added to `nuxt.config.ts`
`experimental: {
    configSchema: true,
  },`

**Comment by manniL** [comment]
@burda-osowiecki Feel free to raise an issue!

**Comment by lionhu** [comment]
@burda-osowiecki 
I ran in same problem, but accidentally solved by only change app.config.ts to app.config.js .
without adding index.d.ts or any change in nuxt.config.js 

You can try it
