### PR TITLE
fix(schema): document use case for `typescript.shim`

### LINKED ISSUE #24311: Disable $fetch function call for prerendered api routes
### Describe the feature

$fetch function calling capabilities in SSR is cool, but when I prerender an expensive route via routeRules I don't want the useFetch composable / $fetch calls to re-run the computation, I want to return the prerendered response.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

### LINKED ISSUE #26311: Bad component types since nuxt `v3.11.0`
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.6.2`
- Nuxt Version:     `3.11.0`
- CLI Version:      `3.10.1`
- Nitro Version:    `2.9.4`
- Package Manager:  `pnpm@8.15.4`
- Builder:          `-`
- User Config:      `app`, `css`, `devtools`, `experimental`, `googleFonts`, `i18n`, `image`, `modules`, `nitro`, `pinia`, `primevue`, `runtimeConfig`, `tailwindcss`, `typescript`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.11.4`, `@nuxt/test-utils/module@3.12.0`, `nuxt-primevue@0.3.1`, `@nuxtjs/i18n@8.2.0`, `@nuxt/image@1.4.0`, `@nuxtjs/google-fonts@3.2.0`, `@aksharahegde/nuxt-glow@1.1.2`, `@pinia/nuxt@0.5.1`
- Build Modules:    `-`

### Reproduction

You can reproduce the issue with my repo on this PR : https://github.com/antoinezanardi/werewolves-assistant-web-next/pull/260

### Describe the bug

When I tried to update to the latest version of nuxt `v3.11.0`, I have encountered an issue which is, I believe, related to components generated types.

When I try to lint the project (with `pnpm run lint:fix`), it warns me that some components I'm using in dynamic imports are of type `any`, even if the application is perfectly building.

Here is an example of the issue in a vue component : 

```vue
<script lang="ts" setup>
import { storeToRefs } from "pinia";

import GameBuryDeadBodiesPlayground from "~/components/pages/game/GamePlaying/GamePlayground/GamePlaygroundContent/GameBuryDeadBodiesPlayground/GameBuryDeadBodiesPlayground.vue";
import GameChooseCardPlayground from "~/components/pages/game/GamePlaying/GamePlayground/GamePlaygroundContent/GameChooseCardPlayground/GameChooseCardPlayground.vue";
import GameChooseSidePlayground from "~/components/pages/game/GamePlaying/GamePlayground/GamePlaygroundContent/GameChooseSidePlayground/GameChooseSidePlayground.vue";
import GameNoActionPlayground from "~/components/pages/game/GamePlaying/GamePlayground/GamePlaygroundContent/GameNoActionPlayground/GameNoActionPlayground.vue";
import GameRequestAnotherVotePlayground from "~/components/pages/game/GamePlaying/GamePlayground/GamePlaygroundContent/GameRequestAnotherVotePlayground/GameRequestAnotherVotePlayground.vue";
import GameTargetPlayground from "~/components/pages/game/GamePlaying/GamePlayground/GamePlaygroundContent/GameTargetPlayground/GameTargetPlayground.vue";
import GameUsePotionsPlayground from "~/components/pages/game/GamePlaying/GamePlayground/GamePlaygroundContent/GameUsePotionsPlayground/GameUsePotionsPlayground.vue";
import GameVotePlayground from "~/components/pages/game/GamePlaying/GamePlayground/GamePlaygroundContent/GameVotePlayground/GameVotePlayground.vue";
import { useGamePlay } from "~/composables/api/game/game-play/useGamePlay";
import type { GamePlayType } from "~/composables/api/game/types/game-play/game-play.types";
import { useGameStore } from "~/stores/game/useGameStore";

type GamePlaygroundTypeComponent =
  | typeof GameBuryDeadBodiesPlayground // 🚨 Starting from here, the components are of type `any` for `eslint` 
  | typeof GameChooseCardPlayground // 🚨
  | typeof GameChooseSidePlayground // 🚨
  | typeof GameNoActionPlayground // 🚨
  | typeof GameRequestAnotherVotePlayground // 🚨
  | typeof GameTargetPlayground // 🚨
  | typeof GameUsePotionsPlayground // 🚨
  | typeof GameVotePlayground; // 🚨

const gameStore = useGameStore();
const { game } = storeToRefs(gameStore);

const { currentPlayType } = useGamePlay(game);

const gamePlaygroundTypeComponentToRender = computed<GamePlaygroundTypeComponent | undefined>(() => {
  const { currentPlay } = game.value;
  if (currentPlay?.action === "use-potions") {
    return GameUsePotionsPlayground;
  }
  const currentGamePlayTypeComponents: Record<GamePlayType, GamePlaygroundTypeComponent> = {
    "bury-dead-bodies": GameBuryDeadBodiesPlayground,
    "choose-card": GameChooseCardPlayground,
    "choose-side": GameChooseSidePlayground,
    "no-action": GameNoActionPlayground,
    "request-another-vote": GameRequestAnotherVotePlayground,
    "target": GameTargetPlayground,
    "vote": GameVotePlayground,
  };

  return currentPlayType.value ? currentGamePlayTypeComponents[currentPlayType.value] : undefined;
});
</script>
```

But this issue doesn't show up only in `eslint`, but even in `stryker-js` (a mutation tests runner). It can't resolve any of the components with the message below : 

```bash
tests/unit/specs/components/layouts/default/NavBar.nuxt.spec.ts(5,20): error TS2307: Cannot find module '~/components/layouts/default/NavBar/NavBar.vue' or its corresponding type declarations.
tests/unit/specs/components/layouts/default/ParametersMenu/ParametersMenu.nuxt.spec.ts(11,28): error TS2307: Cannot find module '~/components/layouts/default/NavBar/ParametersMenu/ParametersMenu.vue' or its corresponding type declarations.
tests/unit/specs/components/pages/about/AboutAvailableRoles/AboutAvailableRoles.nuxt.spec.ts(7,43): error TS2307: Cannot find module '~/components/pages/about/AboutAvailableRoles/AboutAvailableRoleDescription/AboutAvailableRoleDescription.vue' or its corresponding type declarations.
tests/unit/specs/components/pages/about/AboutAvailableRoles/AboutAvailableRoles.nuxt.spec.ts(8,33): error TS2307: Cannot find module '~/components/pages/about/AboutAvailableRoles/AboutAvailableRoles.vue' or its corresponding type declarations.
tests/unit/specs/components/pages/about/AboutAvailableRoles/AboutAvailableRoles.nuxt.spec.ts(9,38): error TS2307: Cannot find module '~/components/shared/misc/TextProgressSpinner/TextProgressSpinner.vue' or its corresponding type declarations.
```

Apart of these tools, the `vitest` can run all tests without errors and the app is starting fine… All of these were working in `v3.10.0` of nuxt.

Is it maybe a problem with the way I'm importing the components in the `vue` and `tests` files ?  I tried to resolve them from the `#components` path, same issue. Maybe I need to add something in the `tsconfig.json` file for correct type resolving ?

Thanks a lot for your help ❤️  

### Additional context

_No response_

### Logs

_No response_
```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by antoinerey**
Closes #26311

~~This reverts commit 280d30d5e1b97c12c0c3ab3fd6833d1cd64d26d9~~.

### CODE REVIEW

**Comment by antfu** [comment]
I suppose this is about ESLint with Type-aware linting enabled? https://typescript-eslint.io/getting-started/typed-linting ?

I personally don't think it's a widespread usage (it significantly slows down). If the trade-off is to have less accurate types for all users - I'd suggest documenting it and asking users to enable it when needed.

**Comment by antfu** [comment]
Meanwhile, I suppose we could find a way to have a better tsconfig setup with `@nuxt/eslint` later on

**Comment by danielroe** [comment]
@antfu Are you suggesting using the shim by default (with less accurate types) and asking users to opt-in to more accurate ones, or the other way around?

**Comment by danielroe** [comment]
Okay, I'll update this PR to improve documentation but not change default.

**Comment by antoinerey** [comment]
> I would prefer to not having the shim by default, and opt-in for users that need to work outside of Volar/`vue-tsc` - which is the current behavior

For what it's worth, our typechecking fails even though we're using the `nuxi typecheck` command. I've created the following minimal reproduction: https://stackblitz.com/edit/nuxt-starter-vvj2wc.

It's a mono-repository with one application and two modules. One module exposes a `HelloWorld` component via its package.json exports property. I'm not exposing the component through the `addComponent` function as I don't want it to be available through `#imports`.

Note that both modules are identical. They both rely on `@nuxt/module-builder` to generate the types and prepare everything. I'm not relying on `nuxi prepare playground` here as there is no playground.

Still, the typechecking steps fail on the consumer app, but also on the consumer module (`module-2`). While there is a way to force the shim generation on the application, there is no such mechanism in the modules.
