### PR TITLE
fix(vite): revert externality

### LINKED ISSUE #30749: Cannot find module './moment-timezone' after upgrading to v3.15.3
### Environment

- Operating System: Linux
- Node Version:     v23.1.0
- Nuxt Version:     3.15.3
- CLI Version:      3.20.0
- Nitro Version:    2.10.4
- Package Manager:  bun@1.1.37
- Builder:          -
- User Config:      future, srcDir, components, devtools, features, app, experimental, dev, ssr, dir, imports, alias, vite, runtimeConfig, css, modules, dayjs, security, googleFonts, piniaPersistedstate, nitro, elementPlus, image, lodash, tailwindcss, postcss, build, hooks, compatibilityDate
- Runtime Modules:  @pinia/nuxt@0.5.5, @pinia-plugin-persistedstate/nuxt@1.2.1, @nuxt/image@1.9.0, nuxt-icon@0.6.10, radix-vue/nuxt@1.9.12, nuxt-monaco-editor@1.3.1, nuxt-purgecss@2.0.0, nuxt-lodash@2.5.3, nuxt-headlessui@1.2.0, nuxt-typed-router@3.7.3, @nuxtjs/google-fonts@3.2.0, @element-plus/nuxt@1.1.1, @vueuse/nuxt@10.11.1, nuxt-security@2.1.5, dayjs-nuxt@2.1.11, ./modules/nucleus
- Build Modules:    -
------------------------------

### Reproduction

bun dev

### Describe the bug

After upgrading to nuxt v3.15.3 I get the following error

`Cannot find module './moment-timezone' Require stack: - /var/www/html/nucleus/moment-timezone `

I'm using momentjs heavily in my project and now it seems like momentjs causing some conflict b/w es and commonjs modules which I'm not sure. if you are aware of this please let me know.

Regards 

### Additional context

_No response_

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by Saeid-Za**
### 🔗 Linked issue

This fixes a regression from https://github.com/nuxt/nuxt/pull/30634 that fixes #30749
Reverting to be dependent on `externality` and `mlly` to determine the absolute path of external packages.

### 📚 Description
There should be a better way, but I frankly don't understand how the default `vite-node` behavior was considered fine in #30634, How does vite-node resolve a module-Id ?

### CODE REVIEW

**Comment by danielroe** [comment]
Of course we need to resolve the linked issue, but it shouldn't be by adding back `externality`.

It seems to be triggered by certain dependences' resolution process (CJS maybe?) and can probably be done with vite-node configuration or a plugin, if absolutely necessary.
