### ISSUE TITLE
Nuxt 3.10 cannot resolve internal Nuxt module imports

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#26219]
### Environment

Stackblitz

```
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    -
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, typescript
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-etc9xo?file=utils%2Fapi.ts

### Describe the bug

This was working in Nuxt 3.9 but with the latest release in Nuxt 3.10 this has been broken. This is because of the change that Nuxt 3.10 made with `moduleResolution` switching from `Node` to `Bundler`.

Setting this future flag to false fixes the issue.

https://nuxt.com/blog/v3-10#bundler-module-resolution

```ts
export default defineNuxtConfig({
  future: {
    typescriptBundlerResolution: false
  }
})
```

This code worked in Nuxt 3.9 but not in Nuxt 3.10
```ts
import type { FetchResult as _FetchResult } from 'nuxt/dist/app/composables/fetch.d.ts'
import type { KeysOf as _KeysOf, PickFrom as _PickFrom } from 'nuxt/dist/app/composables/asyncData'
import type { NitroFetchRequest, AvailableRouterMethod as _AvailableRouterMethod } from 'nitropack'

type ApiStatus = 'start' | 'success' | 'error' | 'end'
type AvailableRouterMethod<R extends NitroFetchRequest> = _AvailableRouterMethod<R> | Uppercase<_AvailableRouterMethod<R>>

export type {
    ApiStatus,
    AvailableRouterMethod,
    _FetchResult,
}
```

Screenshot:
![image](https://github.com/nuxt/nuxt/assets/34019878/ff671265-0a90-45c6-86f1-77dad817864d)

Error:
```ts
[vue-tsc] Cannot find module 'nuxt/dist/app/composables/fetch.d.ts' or its corresponding type declarations.
/home/projects/github-etc9xo/utils/api.ts:1:102
  > 1 | import type { FetchResult as _FetchResult } from 'nuxt/dist/app/composables/fetch.d.ts'
      |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2 | import type { KeysOf as _KeysOf, PickFrom as _PickFrom } from 'nuxt/dist/app/composables/asyncData'
    3 | import type { NitroFetchRequest, AvailableRouterMethod as _AvailableRouterMethod } from 'nitropack'
    4 |
[vue-tsc] Cannot find module 'nuxt/dist/app/composables/asyncData' or its corresponding type declarations.
/home/projects/github-etc9xo/utils/api.ts:2:63
    1 | import type { FetchResult as _FetchResult } from 'nuxt/dist/app/composables/fetch.d.ts'
  > 2 | import type { KeysOf as _KeysOf, PickFrom as _PickFrom } from 'nuxt/dist/app/composables/asyncData'
      |                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    3 | import type { NitroFetchRequest, AvailableRouterMethod as _AvailableRouterMethod } from 'nitropack'
    4 |
    5 | type ApiStatus = 'start' | 'success' | 'error' | 'end'
[vue-tsc] Cannot find module 'nitropack' or its corresponding type declarations.
/home/projects/github-etc9xo/utils/api.ts:3:89
    1 | import type { FetchResult as _FetchResult } from 'nuxt/dist/app/composables/fetch.d.ts'
    2 | import type { KeysOf as _KeysOf, PickFrom as _PickFrom } from 'nuxt/dist/app/composables/asyncData'
  > 3 | import type { NitroFetchRequest, AvailableRouterMethod as _AvailableRouterMethod } from 'nitropack'
      |                                                                                         ^^^^^^^^^^^
    4 |
    5 | type ApiStatus = 'start' | 'success' | 'error' | 'end'
    6 | type AvailableRouterMethod<R extends NitroFetchRequest> = _AvailableRouterMethod<R> | Uppercase<_AvailableRouterMethod<R>>
```

**Comment by danielroe** [comment]
You shouldn't import types from those paths. Instead you could import them from `nuxt/app` or (better) `#app`.

**Comment by martinszeltins** [comment]
> You shouldn't import types from those paths. Instead you could import them from `nuxt/app` or (better) `#app`.

@danielroe Thank you for the response. I did also try importing these types from `#app`, `#imports` and `nuxt/app` but that didn't work. The only one that worked was `FetchResult`.

Is there any other _(more proper)_ place where to import these types from?

**Screenshot showing import errors:**
![image](https://github.com/nuxt/nuxt/assets/34019878/580eb03e-ad49-4cac-9a54-e16df27dd547)

**Comment by danielroe** [comment]
NitroFetchRequest and AvailableRouterMethod both come from 'nitropack'.

You should be able to import KeysOf and Pick from from `#app/composables/asyncData`.

**Comment by martinszeltins** [comment]
Thank you @danielroe! Now the only problem seems to be that it cannot find module `nitropack` itself. This is also caused by the new `Bundler` resolution mode in 3.10. If I change the "moduleResolution" option back to "Node" as it was in Nuxt 3.9 then it works.

![image](https://github.com/nuxt/nuxt/assets/34019878/7b71617f-1b5f-42e8-acbb-85b477f33be0)

**Comment by danielroe** [comment]
@martinszeltins This should be resolved in v3.11 🙏
