### ISSUE TITLE
When upgrade from 3.0-rc14 to v3.1.1,build project debug "can not find module string_decoder".

### ISSUE THREAD

**Issue by tenfei4** [nuxt/nuxt#18721]
### Describe the feature

at v3.0.0-rc14 is ok. when upgrade to v3.1.1,when build project debug:

Nuxt 3.1.1 with Nitro 2.1.1 
Error: Error: Cannot find module string_decoder/ imported from file:///D:/nuxt_app/node_modules, file:///D:/nuxt_app/node_modules/nuxt/node_modules, file:///D:/nuxt_app/node_modules/nitropack/node_modules, file:///D:/nuxt_app/, file:///D:/nuxt_app/node_modules/_index.js, file:///D:/nuxt_app/node_modules, file:///D:/nuxt_app/node_modules/nuxt/, file:///D:/nuxt_app/node_modules/nuxt/node_modules/_index.js, file:///D:/nuxt_app/node_modules/nuxt/node_modules, file:///D:/nuxt_app/node_modules/nitropack/, file:///D:/nuxt_app/node_modules/nitropack/node_modules/_index.js, file:///D:/nuxt_app/node_modules/nitropack/node_modules 
undefined

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by tenfei4** [comment]
when project npm run dev  mode,all right.Only npm run build debug. upgrade v3.-rc.14 to v3.1.1 or create new v3.1.1 project are under debug.

√ Server built in 2840ms                                                                                                                19:06:23  
√ Generated public .output/public                                                                                                 nitro 19:06:23
i Building Nitro Server (preset: node-server)                                                                                     nitro 19:06:23

 ERROR  Error: Error: Cannot find module string_decoder/ imported from file:///D:/nuxt_app/node_modules, file:///D:/nuxt_app/node_modules/nuxt/node_modules, file:///D:/nuxt_app/node_modules/nitropack/node_modules, file:///D:/nuxt_app/, file:///D:/nuxt_app/node_modules/_index.js, file:///D:/nuxt_app/node_modules, file:///D:/nuxt_app/node_modules/nuxt/, file:///D:/nuxt_app/node_modules/nuxt/node_modules/_index.js, file:///D:/nuxt_app/node_modules/nuxt/node_modules, file:///D:/nuxt_app/node_modules/nitropack/, file:///D:/nuxt_app/node_modules/nitropack/node_modules/_index.js, file:///D:/nuxt_app/node_modules/nitropack/node_modules

**undefined**

 ERROR  Error: Cannot find module string_decoder/ imported from file:///D:/nuxt_app/node_modules, file:///D:/nuxt_app/node_modules/nuxt/node_modules, file:///D:/nuxt_app/node_modules/nitropack/node_modules, file:///D:/nuxt_app/, file:///D:/nuxt_app/node_modules/_index.js, file:///D:/nuxt_app/node_modules, file:///D:/nuxt_app/node_modules/nuxt/, file:///D:/nuxt_app/node_modules/nuxt/node_modules/_index.js, file:///D:/nuxt_app/node_modules/nuxt/node_modules, file:///D:/nuxt_app/node_modules/nitropack/, file:///D:/nuxt_app/node_modules/nitropack/node_modules/_index.js, file:///D:/nuxt_app/node_modules/nitropack/node_modules

  at resolvePath (/D:/nuxt_app/node_modules/mlly/dist/index.mjs:1863:10)
  at _resolve (/D:/nuxt_app/node_modules/nitropack/dist/shared/nitro.e7dc7fe5.mjs:365:22)
  at Object.resolveId (/D:/nuxt_app/node_modules/nitropack/dist/shared/nitro.e7dc7fe5.mjs:418:34)
  at async PluginDriver.hookFirstAndGetPlugin (/D:/nuxt_app/node_modules/rollup/dist/es/shared/rollup.js:23685:28)
  at async resolveId (/D:/nuxt_app/node_modules/rollup/dist/es/shared/rollup.js:22629:26)
  at async ModuleLoader.resolveId (/D:/nuxt_app/node_modules/rollup/dist/es/shared/rollup.js:22893:15)
  at async /D:/nuxt_app/node_modules/@rollup/plugin-commonjs/dist/es/index.js:778:16
  at async Promise.all (index 11)
  at async /D:/nuxt_app/node_modules/@rollup/plugin-commonjs/dist/es/index.js:770:32
  at async rewriteRequireExpressionsAndGetImportBlock (/D:/nuxt_app/node_modules/@rollup/plugin-commonjs/dist/es/index.js:1316:28)

**package.json**
{
  "private": true,
  "scripts": {
    "dev": "nuxt dev",
    "build": "nuxt build",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^6.1.3",
    "nuxt": "^3.1.1",
    "nuxt-lazyimages": "^0.2.0"
  },
  "dependencies": {
    "@ckeditor/ckeditor5-build-balloon": "^35.4.0",
    "@ckeditor/ckeditor5-vue": "^4.0.1",
    "@fortawesome/fontawesome-svg-core": "^6.2.0",
    "@fortawesome/free-brands-svg-icons": "^6.2.0",
    "@fortawesome/free-regular-svg-icons": "^6.2.0",
    "@fortawesome/free-solid-svg-icons": "^6.2.0",
    "@fortawesome/vue-fontawesome": "^3.0.2",
    "axios": "^1.1.3",
    "bignumber.js": "^9.1.1",
    "cropperjs": "^1.5.12",
    "mysql": "^2.18.1",
    "nodemailer": "^6.8.0",
    "redis": "^4.4.0",
    "sharp": "^0.31.3",
    "vue-img-viewr": "^2.0.11",
    "vue3-toastify": "^0.0.3"
  }
}

**Comment by manniL** [comment]
@tenfei4 this is not a reproduction though. Please check the linked instructions above ☺️

**Comment by madebyfabian** [comment]
Try to undo the upgrade, manually delete your `.nuxt`, `.output` and `package-lock.json` and try to upgrade via `npm i nuxt@latest`.

**Comment by tenfei4** [comment]
yes tried do that n times,it's also not work.only at v3.0.0-rc.14 all ok. upgrade v3.11 or v3.12 ,at dev mode,is ok,only debug at build mode.   if delete project/server folder,it's ok.

**Comment by madebyfabian** [comment]
Try to upgrade to nuxt 3.0.0 first and then check if it also happens

**Comment by tenfei4** [comment]
upgrade version from v3.0-rc.14 to v3.0.0,all ok,but upgrade to v3.11,is wrong. and i found error from:
170 lines of .output/server/node_modules/readable_stream/lib/_stream_readable.js
  if (options.encoding) {
    if (!StringDecoder) StringDecoder = require(**'string_decoder/'**).StringDecoder;
    this.decoder = new StringDecoder(options.encoding);
    this.encoding = options.encoding;
  }

**Comment by madebyfabian** [comment]
I understand this is frustrating. These errors typically either come from nuxts dependencies not being synced, but you've said you have done that clean install I suggested. So I am not an absolute expert in those error messages and the message alone is pretty useless to without context.

What do you mean with `if delete project/server folder,it's ok.`?

You can now try to incrementially upgrade, but don't forget to do this every time https://github.com/nuxt/nuxt/issues/18721#issuecomment-1416724266

So you could now go from 3.0.0 to the next patch release. Available. You can also disable all/parts of your modules.

**Comment by tenfei4** [comment]
i mean, if i delete ./server folder then built,its done.

**Comment by madebyfabian** [comment]
@tenfei4 So this sounds like t's probably a module/piece of code inside that `./server` that is maybe deprecated or the syntax has changed.

**Comment by tenfei4** [comment]
Use v3.0.0 for the time being. Thank you very much anyway.

**Comment by madebyfabian** [comment]
Okay, then the issue could be closed I guess for now

**Comment by tenfei4** [comment]
I have found the reason for the error and share it here. Due to the mysql v2.18.1 component version conflict, an error is reported during project build, the specific reason will not be quit here, and the solution can be replaced by mysql2 v3.1.0 component.
