### ISSUE TITLE
Decorators with generics not work in v3.7.4

### ISSUE THREAD

**Issue by yaquawa** [nuxt/nuxt#23686]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-bwwkvq?file=app%2Fdecorators.ts

### Describe the bug

Decorators with generics will give this error:
```
/home/projects/github-bwwkvq/app/decorators.ts:10:12: ERROR: Expected identifier but found "<"
```

Without the generics, it will work. This issue doesn't exist in version 3.6.5

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/14126
