### ISSUE TITLE
Nuxt >=3.6.5 : Cannot find module and RollupError: Could not resolve

### ISSUE THREAD

**Issue by alimozdemir** [nuxt/nuxt#22958]
### Environment

My local

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.5.1
- Builder:          -
- User Config:      modules, image, vite, extends, experimental, routeRules, nitro, sitemap, css, runtimeConfig, devtools
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @vueuse/nuxt@10.1.2, @pinia/nuxt@0.4.11, @nuxt/image@1.0.0-rc.1, nuxt-simple-sitemap@2.7.0
- Build Modules:    -
------------------------------

Reproduction
------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    -
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-f5iwgw?file=app.vue

### Describe the bug

In my local, I'm receiving the following error first

```

 ERROR  RollupError: Could not resolve "./AutoCollection/CorrelationContextManager" from "./AutoCollection/CorrelationContextManager?commonjs-external"   nitro 12:06:28

                                                                                                                                                                12:05:54  
undefined

```

Then whenever I open the webpage it gives me following error

Cannot find module './AutoCollection/CorrelationContextManager' Require stack: - /home/projects/nuxt-starter-f5iwgw/applicationinsights

![image](https://github.com/nuxt/nuxt/assets/4493134/3c42417a-4dc6-46d5-ac8c-b08dbf8cf5ad)

### Additional context

I tested with Nuxt 3.6.5 and Nuxt 3.7.0.

**It works in 3.5.3 without any issues.**

**Comment by peteromano** [comment]
Could this be related to 3.7 issue https://github.com/nuxt/nuxt/issues/22918

?

**Comment by alimozdemir** [comment]
@peteromano it might be, but this is not working with 3.6.5 I'm pretty sure about it.  There is a rollup error in my case as well.

If the both 3.6.5 and 3.7.0 uses the same vite-node version then it might be the same.

**Comment by danielroe** [comment]
Does this replicate if you do not name your project folder `applicationinsights`?

**Comment by alimozdemir** [comment]
As I see, it is labeled as a minor bug on vite. Should I link this issue to vite repository? Are they going to fix it or nuxt team is going to fix it? @danielroe

**Comment by danielroe** [comment]
In this case it just means that the error is being emitted from our vite-node integration. I'm not in fact sure whether this is a Nuxt issue or elsewhere.

In any case, it can be worked around with:

```ts
export default defineNuxtConfig({
  build: {
    transpile: ['applicationinsights']
  }
})
```

**Comment by alimozdemir** [comment]
It seems like it might be workaround in the reproduction. I just tested there and it seems like it is working.

In my local (windows)

I received this error

```
 ERROR  [worker reload] [worker init] __dirname is not defined in ES module scope                                                                                                                   15:19:25

  at JsonConfig._loadJsonFile (/.nuxt/dev/index.mjs:1856:40)
  at new JsonConfig (/.nuxt/dev/index.mjs:1838:14)
  at JsonConfig.getInstance (/.nuxt/dev/index.mjs:1842:36)
  at /.nuxt/dev/index.mjs:1983:51
  at /.nuxt/dev/index.mjs:2023:3
  at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

```

**Comment by alimozdemir** [comment]
> It seems like it might be workaround in the reproduction. I just tested there and it seems like it is working.
> 
> In my local (windows)
> 
> I received this error
> 
> ```
>  ERROR  [worker reload] [worker init] __dirname is not defined in ES module scope                                                                                                                   15:19:25
> 
>   at JsonConfig._loadJsonFile (/.nuxt/dev/index.mjs:1856:40)
>   at new JsonConfig (/.nuxt/dev/index.mjs:1838:14)
>   at JsonConfig.getInstance (/.nuxt/dev/index.mjs:1842:36)
>   at /.nuxt/dev/index.mjs:1983:51
>   at /.nuxt/dev/index.mjs:2023:3
>   at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
> ```

I was developing applicationinsight as a separated `extends`. I think this is the issue whenever I put transpile configuration as you suggest. I just moved everything outside of `extend` then it started to work.

**Comment by danielroe** [comment]
Would you provide a more precise reproduction in that case?

**Comment by alimozdemir** [comment]
Currently, I'm facing this issue even if it is used by "extends" or not. I think this is related to https://github.com/unjs/nitro/issues/808

@danielroe any news on it?

**Comment by alimozdemir** [comment]
@danielroe reproduction link for "__dirname" problem on linux

https://stackblitz.com/edit/nuxt-starter-cdamuw?file=modules%2Fappinsight%2Fserver%2Fmiddleware%2Fappinsight.ts

**Comment by danielroe** [comment]
let's track upstream in https://github.com/unjs/nitro/issues/1726.
