### ISSUE TITLE
nuxt 3.6.5 generate

### ISSUE THREAD

**Issue by gllinzbk1** [nuxt/nuxt#22639]
### Environment

nuxt3.6.5
nitro:2.5.2
vite v4.3.9

### Reproduction

(https://github.com/gllinzbk1/nuxtgenerate)

### Describe the bug

nuxt3.6.5
npm run generate 
get 500,and stop work

but nuxt3.5.3  

npm run generate 
it's ok

**Comment by Barbapapazes** [comment]
Hello, I think that content is missing in your reproduction!

**Comment by gllinzbk1** [comment]
> Hello, I think that content is missing in your reproduction!

pls try again.

**Comment by Barbapapazes** [comment]
> > Hello, I think that content is missing in your reproduction!
> 
> pls try again.

That's good!

**Comment by gllinzbk1** [comment]
> > > Hello, I think that content is missing in your reproduction!
> > 
> > 
> > pls try again.
> 
> That's good!

now nuxt3.5.3 it work well,just update nuxt3.6.5,that's not work well.

**Comment by Barbapapazes** [comment]
You clearly have a loop in your code. Try to fixe it!

![image](https://github.com/nuxt/nuxt/assets/45267552/d74bc69c-2879-4ca5-9686-4cabbd15c872)

**Comment by gllinzbk1** [comment]
> You clearly have a loop in your code. Try to fixe it!
> 
> ![image](https://user-images.githubusercontent.com/45267552/260677572-d74bc69c-2879-4ca5-9686-4cabbd15c872.png)

it can work in nuxt3.5.3,but not work in nuxt3.6.5, because have a loopm in nuxt3.6.5?

**Comment by alexmercier25** [comment]
I have the same issue but only when deployed to Vercel! Getting 500 error.

Here's the logs:

```
[nuxt] [request error] [unhandled] [500] Cannot find module '/var/task/node_modules/tslib/modules/index.js' imported from /var/task/chunks/app/server.mjs
Did you mean to import tslib/tslib.js?
  at new NodeError (node:internal/errors:399:5)  
  at finalizeResolution (node:internal/modules/esm/resolve:331:11)  
  at moduleResolve (node:internal/modules/esm/resolve:994:10)  
  at moduleResolveWithNodePath (node:internal/modules/esm/resolve:938:12)  
  at defaultResolve (node:internal/modules/esm/resolve:1202:79)  
  at nextResolve (node:internal/modules/esm/loader:163:28)  
  at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)  
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)  
  at link (node:internal/modules/esm/module_job:76:36)
[nuxt] [request error] [unhandled] [500] Cannot find module '/var/task/node_modules/tslib/modules/index.js' imported from /var/task/chunks/app/server.mjs
Did you mean to import tslib/tslib.js?
  at new NodeError (node:internal/errors:399:5)  
  at finalizeResolution (node:internal/modules/esm/resolve:331:11)  
  at moduleResolve (node:internal/modules/esm/resolve:994:10)  
  at moduleResolveWithNodePath (node:internal/modules/esm/resolve:938:12)  
  at defaultResolve (node:internal/modules/esm/resolve:1202:79)  
  at nextResolve (node:internal/modules/esm/loader:163:28)  
  at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)  
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)  
  at link (node:internal/modules/esm/module_job:76:36)

```

**Comment by cqh-git** [comment]
我也遇到这个问题了
![image](https://github.com/nuxt/nuxt/assets/59131766/fad06eff-dee1-43d1-845d-62dc343face1)

**Comment by alexmercier25** [comment]
I think this is quite a big issue. I can't deploy to vercel anymore since I've upgraded Nuxt. Even if I try to downgrade. My only option was to do an instant rollback of when it worked. But now I'm stuck, I can't update my website. This is really weird..

**Comment by cqh-git** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，你的邮件我已收到，看到后第一时间回复你

**Comment by gllinzbk1** [comment]
@danielroe
Can you help confirm if there is a version compatibility issue or a code issue

**Comment by danielroe** [comment]
1. remove `@nuxt/types` - this is a Nuxt 2 package
2. remove `@nuxtjs/proxy` - this is a Nuxt 2 package
3. You do not need to JSON.parse the response of `useFetch`. It is already parsed, as long as there are correct `content-type` headers. If not, you can force with `responseType: 'json'`.

With these changes, everything works fine.

**Comment by gllinzbk1** [comment]
in nuxt3.6.5
![image](https://github.com/nuxt/nuxt/assets/115514156/26e38a8e-daa0-46dc-87c3-5aa030bcff86)

**Comment by gllinzbk1** [comment]
Reproduction "nuxt": "^3.5.3",

**Comment by danielroe** [comment]
@gllinzbk1 Do feel free to provide a minimal reproduction. When I added `responseType: 'json'` and didn't try to parse data that already existed, everything worked fine in your link repo with latest Nuxt (3.6.5).

**Comment by gllinzbk1** [comment]
sorry,just npm run generate ，will show 500 error

**Comment by gllinzbk1** [comment]
(https://github.com/gllinzbk1/nuxtgenerate) i update a version ,can you try it

**Comment by gllinzbk1** [comment]
![image](https://github.com/nuxt/nuxt/assets/115514156/e75006e1-d61a-4682-b1b3-7ffa6b6895f6)
get data from server/api

**Comment by gllinzbk1** [comment]
![image](https://github.com/nuxt/nuxt/assets/115514156/1e80e3f0-4808-482b-bbdb-00502bd9b6d8)
npm run dev  is ok
npm run generate ,get 500 error and stop work

**Comment by gllinzbk1** [comment]
![image](https://github.com/nuxt/nuxt/assets/115514156/c13ebae0-b2b7-4161-91fc-ed350d2e81ee)

https://shiny-journey-qjrxrjv5pqqfx577.github.dev/

**Comment by gllinzbk1** [comment]
![image](https://github.com/nuxt/nuxt/assets/115514156/0cf7d0a9-ec50-45e1-a784-5cb8789ef147)
When clicking on the homepage (click: carbon mountain bike) for the first time, the data obtained from the server/API was incorrect. The reason for the error is this screenshot. When refreshing, it will be normal
![image](https://github.com/nuxt/nuxt/assets/115514156/2b83f84b-ea4f-4005-ac7f-c4b7717d9703)

**Comment by gllinzbk1** [comment]
init data
![image](https://github.com/nuxt/nuxt/assets/115514156/3bba2340-2fd8-449b-80ad-88aa7190586a)

**Comment by gllinzbk1** [comment]
![image](https://github.com/nuxt/nuxt/assets/115514156/7f50a01c-957e-469b-82f8-4154855434db)
Why did the initialization fail due to the failure of automatic import of stores, so there is no state in the data
@danielroe

**Comment by gllinzbk1** [comment]
![image](https://github.com/nuxt/nuxt/assets/115514156/46349eaa-2f01-44a7-b176-8464760d63a7)
is it route problem?

**Comment by gllinzbk1** [comment]
> Here you go: https://stackblitz.com/edit/github-fjfqqk?file=composables/useProduct.js,stores/sql.js,nuxt.config.ts. It finishes generation successfully now.
> 
```
export const getStoreById = (id: string) => {
    //@ts-expect-error _s is internal
    return getActivePinia()?._s.get(id);
};
```
Method to obtain data only once
![image](https://github.com/nuxt/nuxt/assets/115514156/5816092f-8afd-4148-8c7c-805c75220085)

**Comment by gllinzbk1** [comment]
nuxt3.60,3.6.1 its ok
nuxt3.6.2-5 ,its not normally
