### ISSUE TITLE
After upgrading Nuxt 3.0.0 to 3.2.0 problem

### ISSUE THREAD

**Issue by regchiu** [nuxt/nuxt#18933]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `app`, `typescript`, `runtimeConfig`, `modules`, `colorMode`, `tailwindcss`
- Runtime Modules:  `@nuxtjs/color-mode@3.2.0`, `nuxt-icon@0.1.8`, `@nuxtjs/tailwindcss@6.1.3`, `@pinia/nuxt@0.4.6`
- Build Modules:    `-`
------------------------------

### Reproduction

1. `yarn upgrade nuxt --latest`
2. `yarn dev`
```
 ERROR  Cannot start nuxt:  Cannot find module 'postcss-custom-properties'
```
3. Open `nuxt.config.ts` will see this on the `colorMode` property.
```
Argument of type '{ app: { head: { link: { rel: "icon"; type: "image/svg+xml"; href: string; }[]; }; }; typescript: { shim: false; strict: true; }; runtimeConfig: { apiSecret: string; public: { apiBase: string; }; }; modules: (string | [...])[]; colorMode: { ...; }; tailwindcss: { ...; }; }' is not assignable to parameter of type 'NuxtConfig'.
  Object literal may only specify known properties, and 'colorMode' does not exist in type 'NuxtConfig'.
```

### Describe the bug

After upgrading nuxt `3.0.0` to `3.2.0`, will see the problems.

1. `colorMode` module option in nuxt `3.0.0` shows the type as
```
(property) NuxtConfig['colorMode']?: Partial<ModuleOptions> | undefined
```
but shows error in nuxt `3.2.0`.

2. We need to install `postcss-custom-properties` in nuxt `3.2.0`, didn't need it in nuxt `3.0.0`.

**Comment by harlan-zw** [comment]
@regchiu Try upgrading @nuxtjs/tailwindcss to the latest. Otherwise please create a reproduction repo

**Comment by regchiu** [comment]
The repo is here.

rep: https://github.com/regchiu/nuxt3-starter-template

Just run `yarn upgrade nuxt --latest` then run `yarn dev`, you can see:

1. `colorMode ` type error in `nuxt.config.ts` file. This doesn't affect program work, but typescript type error can be a bit annoying.

![](https://user-images.githubusercontent.com/25433868/218125273-ca75d5ed-6765-4f01-adfc-21c5b8d2a5cd.jpg)

2. postcss-custom-properties error. This does not need to be installed in nuxt 3.0.0 version.

![SharedScreenshot2](https://user-images.githubusercontent.com/25433868/218126142-86749ab2-a1ca-4fa6-ad3e-79881ed5564d.jpg)

So I need to upgrade all of nuxt module packages?  thank you for your help.

**Comment by harlan-zw** [comment]
Yes try upgrading and then see what issues are left

**Comment by JokerMartini** [comment]
did upgrading fix all the issues?

**Comment by regchiu** [comment]
> did upgrading fix all the issues?

@JokerMartini Try `nuxi upgrade --force`.
