### ISSUE TITLE
Excessive stack depth comparing types in `useFetch`

### ISSUE THREAD

**Issue by mahdiboomeri** [nuxt/nuxt#18570]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `pnpm@7.25.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/mahdiboomeri/nuxt-excessive-stack-depth

### Describe the bug

When using `useFetch` with explicit method in combination of trpc client in a plugin, the following type error occurs on `useFetch`.
```bash
Excessive stack depth comparing types. ts(2321)
```
My best guess is that this is a regression from https://github.com/unjs/nitro/pull/686 and not directly related to trpc.

### Logs

```shell-script
pages/authentication.vue:6:7 - error TS2321: Excessive stack depth comparing types 'Exclude<ReqT extends "/api/test" ? { key: "/api/test"; exact: true; score: []; catchAll: false; } : { key: "/api/test"; exact: false; score: `${ReqT}/` extends `${infer RouteSeg}/${infer RouteRest}` ? `${RouteSeg}?` extends `${infer RouteSegWithoutQuery}?${string}` ? RouteSegWithoutQuery extends "" ? `${RouteRest}/`...' and '{ score: MaxTuple<((ReqT extends "/api/test" ? { key: "/api/test"; exact: true; score: []; catchAll: false; } : { key: "/api/test"; exact: false; score: `${ReqT}/` extends `${infer RouteSeg}/${infer RouteRest}` ? `${RouteSeg}?` extends `${infer RouteSegWithoutQuery}?${string}` ? RouteSegWithoutQuery extends "" ? `${...'.

6 await useFetch("/api/test", {
        ~~~~~~~~~~~~~~~~~~~~~~~
7   method: "POST",
  ~~~~~~~~~~~~~~~~~
8 });
```

**Comment by PatSosna** [comment]
I have a similar problem, and I'm not using trpc. (v3.1.1)

```ts
import { type FetchOptions } from 'ofetch';

export const useFetchOnboarding = (path: string, options?: FetchOptions) => {
  const config = useRuntimeConfig();

  return $fetch(`${config.public.apiUrl}/${path}`, {
    method: 'POST',
    /*  headers: {
      Authorization: `Bearer ${config.public.authToken}`
    }, */
    ...options
  });
};
```

LOG
```log
(property) NitroFetchOptions<`${string}/${string}`>.method?: "POST" | "GET" | "HEAD" | "PATCH" | "PUT" | "DELETE" | "CONNECT" | "OPTIONS" | "TRACE" | "post" | "get" | "head" | "patch" | "put" | "delete" | "connect" | "options" | "trace" | undefined
A string to set request's method.

Type 'string' is not assignable to type '"POST" | "GET" | "HEAD" | "PATCH" | "PUT" | "DELETE" | "CONNECT" | "OPTIONS" | "TRACE" | "post" | "get" | "head" | "patch" | "put" | "delete" | "connect" | "options" | "trace" | undefined'.ts(2322)
````

**Comment by mas-iota** [comment]
I am having the same issue after upgrading to nuxt 3.1.1

**Comment by mahdiboomeri** [comment]
The issue seems to be fixed in the edge channel

**Comment by PatSosna** [comment]
It still doesn't work for me on 3.2.0

**Comment by tiborpino** [comment]
Same for me on 3.2.0
![SCR-20230210-fiq](https://user-images.githubusercontent.com/169465/218064689-03ebea27-09da-4545-a0cf-1bc91df168e8.png)

**Comment by danielroe** [comment]
I can't replicate on the edge channel or on v3.3.2.

If you are still experiencing this, please do provide a reproduction and I'll happily reopen.

**Comment by dargmuesli** [comment]
For anyone landing here having the issue with `$fetch` instead of `useFetch`: check out https://github.com/unjs/nitro/issues/470

**Comment by Suniron** [comment]
Same issue in a Nuxt Bridge project, i want to wrap my `$fetch` like this:

```ts
const useApiFetcher: typeof $fetch = (url, options) => $fetch(url, {
  baseUrl: useRuntimeConfig().public.backendBrowserBaseUrl,
  ...options,
})
```

**Comment by yauheniv** [comment]
It's actual for me on Nuxt 3.5.2
error TS2321: Excessive stack depth comparing types 'Exclude<{ key: "/robots.txt"; exact: false; score: `${?}/` extends `${infer RouteSeg}/${infer RouteRest}` ? `${RouteSeg}?` extends `${infer RouteSegWithoutQuery}?${string}` ? RouteSegWithoutQuery extends "" ? `${RouteRest}/` extends `${infer RouteSeg}/${infer RouteRest}` ? `${RouteSeg}?` extends `${infer RouteSegWit...' and '{ score: MaxTuple<((? extends "/__nuxt_error" ? { key: "/__nuxt_error"; exact: true; score: []; catchAll: false; } : { key: "/__nuxt_error"; exact: false; score: `${?}/` extends `${infer RouteSeg}/${infer RouteRest}` ? `${RouteSeg}?` extends `${infer RouteSegWithoutQuery}?${string}` ? RouteSegWithoutQuery extends ""...'.

  6   return useFetch(request, {
             ~~~~~~~~~~~~~~~~~~~
  7     baseURL: customizationStore.baseUrl,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 50     },
    ~~~~~~
 51   });

**Comment by 4ndre4s** [comment]
Any updates on this?

**Comment by Ayfri** [comment]
Still getting this problem in 3.19.1.

**Comment by HELWATANY** [comment]
Still getting the same error in 3.19.2

**Comment by wokalek** [comment]
Still have this error via `typecheck`

**Comment by LuizSaydt** [comment]
Using Nuxt 4.0.3, same problem whith `useAsyncData`. Seems to only occur when using the options parameter, and it doens't matter what options i use. BUT, if I have two useAsyncData on the same component and i just put something on the options parameter of this second one, it just works, even if is an empty object:

<img width="1120" height="617" alt="Image" src="https://github.com/user-attachments/assets/5e66759f-87be-473a-bbf4-4ed9d27302f9" />

<img width="1119" height="615" alt="Image" src="https://github.com/user-attachments/assets/0625af5f-2eae-4964-b64b-9e7b3182963b" />
