### ISSUE TITLE
3.1.1 - Typing AppConfig stopped work after upgrade

### ISSUE THREAD

**Issue by burda-osowiecki** [nuxt/nuxt#18555]
### Environment

*

### Reproduction

*

### Describe the bug

After updating from 3.0.0 to 3.1.1
I'm getting errors from vue-tsc like Property 'x' does not exist on type 'AppConfig' 

I was trying to declare interface AppConfigInput in index.d.ts like here
https://nuxt.com/docs/guide/directory-structure/app-config#manually-typing-app-config
I also added to nuxt.config.ts
experimental: { configSchema: true, },

insideapp.config.ts I have an empty object.
export default defineAppConfig({})
I'm setting appConfig dynamically based on process.env (in nuxt.config.ts), ofc it has valid types there
But it should be merged anyway.

https://github.com/nuxt/nuxt/pull/18410#issuecomment-1405038775

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by burda-osowiecki** [comment]
nvm, fixed by recreating package-lock ...

**Comment by Tarocch1** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

Same issue after install `@nuxt/content`

reproduction: https://stackblitz.com/edit/github-71dyj4

@danielroe

**Comment by gyhyfj** [comment]
same problem at 3.3.1
